var Common=function(){};Common.removeTweens=function(a,b){if(a.numChildren)for(var c=0;c<a.numChildren;c++)Common.removeTweens(a.getChildAt(c),b);if(!a.persistant||b)createjs.Ticker.removeEventListener("tick",a),createjs.Tween.removeTweens(a)};window.addEventListener("resize",resize);function initCanvas(){StageManager.init("canvas");StageManager.idle()}function resize(){StageManager.resize()}
function showDebugInformation(){setTimeout(function(){var a=createjs.Ticker.getMeasuredFPS(),a=Math.round(100*a)/100;console.log("FPS: "+a+" | Active tweens: "+createjs.Tween._tweens.length+" | Ticker job count: "+createjs.Ticker._listeners.tick.length);showDebugInformation()},1E3)}var MessageInterpreter=function(){};
MessageInterpreter.interpret=function(a){switch(a.cmd){case "show":StageManager.draw(this.getScreen(a),a.overlay);break;case "update":StageManager.update(a);break;case "expand":StageManager.expandOverlay();break;case "minify":StageManager.minifyOverlay();break;case "remove":StageManager.removeOverlay();break;default:console.log("Error: Unknown command "+a.cmd)}};
MessageInterpreter.getScreen=function(a){try{return eval("(new "+a.screen+"(data))")}catch(b){try{return new window[a.screen](a)}catch(c){return console.log("ReferenceError: Screen "+a.screen+" is not defined."),null}}};var BuildPairs=function(a){this._data=a;this._selected={};this._drawable=[];this._submitted=this._initialized=!1};
BuildPairs.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background3.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new WordPairs(this._data.answers,
this.selected.bind(this)));this._drawable.push(new SubmitButton(this.submit.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._drawable.push(new WordPairs(this._data.answers,null))}this._initialized=!0};
BuildPairs.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
BuildPairs.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "SubmitButton":a.x=b.width;a.y=b.height;break;case "WordPairs":a.x=b.width/2,a.y=.7*b.height}};
BuildPairs.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};BuildPairs.prototype.selected=function(a){this._selected=a};
BuildPairs.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd())}};var BuildPairsSolution=function(a){this._data=a;this._drawable=[];this._initialized=!1};
BuildPairsSolution.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background3.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._drawable.push(new WordPairs(this._data.answers,null,this._data.solution));"student"===this._data.view&&this._drawable.push(new HeaderDisplay("Score: +"+this._data.score));this._initialized=!0};
BuildPairsSolution.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
BuildPairsSolution.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "WordPairs":a.x=b.width/2,a.y=.7*b.height}};var CatchEmAll=function(a){this._data=a;this._hitList=[];this._missList=[];this._drawable=[];this._submitted=this._initialized=!1};
CatchEmAll.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/apple-tree.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),
this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer)}this._movingPlatform=new MovingPlatform;this._drawable.push(this._movingPlatform);this._drawable.push(new CatchField(this._data.answers,this._data.difficulty,this.hitTest.bind(this)));this._initialized=!0};CatchEmAll.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
CatchEmAll.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "CatchField":a.x=0;a.y=0;break;case "MovingPlatform":a.x=0,a.y=0}};
CatchEmAll.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};
CatchEmAll.prototype.hitTest=function(a){var b=a.x,c=a.width/2;a=a.text;if(this._movingPlatform.hitTestBetween(b-c,b+c))return 0>this._hitList.indexOf(a)&&this._hitList.push(a),!0;0>this._missList.indexOf(a)&&this._missList.push(a);return!1};
CatchEmAll.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"hits" : '+JSON.stringify(this._hitList)+',"misses" : '+JSON.stringify(this._missList)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd())}};var CatchEmAllSolution=function(a){this._data=a;this._drawable=[];this._initialized=!1};
CatchEmAllSolution.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/apple-tree.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._drawable.push(new CorrectWrongDisplay(this._data.answers));"student"===this._data.view&&this._drawable.push(new HeaderDisplay("Score: +"+this._data.score));this._initialized=!0};
CatchEmAllSolution.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
CatchEmAllSolution.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "CorrectWrongDisplay":a.x=0,a.y=0}};var BackgroundImage=function(a){this._imagePath=a};BackgroundImage.prototype.addTo=function(a){this._container=a;a.name="BackgroundImage";this.createBackgroundImage(a.width,a.height,this._imagePath)};
BackgroundImage.prototype.createBackgroundImage=function(a,b,c){var d=new createjs.Bitmap(c);d.image.onload=function(){d.scaleX=a/d.image.width;d.scaleY=b/d.image.height;this._container.addChild(d)}.bind(this);return d};var ButtonPanel=function(a,b,c,d){this._values=a;this._minified=b;this._setSelected=c;this._stats=d;this._buttons=[];this._initialized=!1};
ButtonPanel.prototype.addTo=function(a){a.name="ButtonPanel";var b=a.width>=a.height,c=a.width;this._minified&&b&&(c/=2);var d=a.height/2;this._minified&&!b&&(d*=.7);var e=a.width/60,g=a.height/50,f=this._values.length,b=this._minified||!b?1:2,k=Math.ceil(f/b),l=(c-e*(b+3))/b,k=(d-g*(k+3))/k,c=this.createMasterPanel(c-2*e,d-2*g);a.addChild(c);if(0<this._buttons.length){for(var m=[],d=0;d<this._buttons.length;d++)m.push(null!=this._buttons[d].clicked);this._buttons=[]}for(d=0;d<f;d++){var h=this._values[d],
p=d%b,q=Math.floor(d/b),n=void 0;void 0!=this._stats&&(n=this._stats[d].correct);var r=void 0==m?!1:m[d],n=this.createButtonPanel(l,k,void 0!=this._stats?this._stats[d].selected:!1,n);n.x=e+p*(e+l)+c.x;n.y=g+q*(g+k)+c.y;n.label=h.toString();this._buttons.push(n);r&&n.dispatchEvent("click");h=this.createButtonLabel(l-e,k,h);h.x=n.x+l/2;p=h.getMeasuredHeight()/h.lineHeight;h.y=n.y+k/2-(p-1)*h.lineHeight/2;a.addChild(n,h);void 0!=this._stats&&this.createStats(a,n,this._stats[d].amount,this._stats[d].selected)}this._initialized=
!0};ButtonPanel.prototype.createMasterPanel=function(a,b){var c=new createjs.Shape;c.graphics.beginFill("#d3d3d3").drawRect(0,0,a,b);c.x=-a/2;c.y=-b/2;c.alpha=.4;return c};
ButtonPanel.prototype.createButtonPanel=function(a,b,c,d){function e(a){null==a.target.clicked?(a.target.filters=[new createjs.ColorFilter(0,0,0,1,255,203,151,0)],a.target.clicked=1):(a.target.filters=a.isTouch?[new createjs.ColorFilter(1,1,1,1,0,0,0,0)]:[new createjs.ColorFilter(1,1,1,1,-25,-25,-25,0)],a.target.clicked=null);a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h);a=[];for(var b=0;b<this._buttons.length;b++)null!=this._buttons[b].clicked&&a.push(this._buttons[b].label);
this._setSelected(a)}function g(a){if(null==a.target.clicked){switch(a.type){case "mouseover":a.target.filters=[new createjs.ColorFilter(1,1,1,1,-25,-25,-25,0)];break;case "mouseout":a.target.filters=[new createjs.ColorFilter(1,1,1,1,0,0,0,0)]}a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h)}}var f=new createjs.Shape;void 0==d?f.graphics.beginFill("#d3d3d3"):d?c?f.graphics.beginFill("#5cb85c"):(f.graphics.beginFill("#d3d3d3"),f.filters=[new createjs.ColorFilter(1,1,1,1)],
f.cache(0,0,a,b),f.handleEvent=function(){this.updateCache()},createjs.Ticker.addEventListener("tick",f),createjs.Tween.get(f,{loop:!0}).wait(200).call(function(a){createjs.Tween.get(a,{loop:!1}).to({redMultiplier:.36,greenMultiplier:.72,blueMultiplier:.36},400,createjs.Ease.getPowInOut(2)).to({redMultiplier:1,greenMultiplier:1,blueMultiplier:1},400,createjs.Ease.getPowInOut(2))},[f.filters[0]]).wait(800)):c?f.graphics.beginFill("#f5756e"):f.graphics.beginFill("#d3d3d3");f.graphics.drawRect(0,0,a,
b);f.width=a;f.height=b;f.shadow=new createjs.Shadow("#333333",5,5,10);null!=this._setSelected&&(f.on("click",e.bind(this)),f.on("mouseover",g.bind(this)),f.on("mouseout",g.bind(this)));return f};ButtonPanel.prototype.createButtonLabel=function(a,b,c){var d=40,e=new createjs.Text;e.text=c.toString();e.font=d+"px Dimbo";e.lineWidth=a;e.lineHeight=1.5*d;e.color="black";e.textAlign="center";for(e.textBaseline="middle";e.getMeasuredHeight()>b;)d-=2,e.lineHeight=1.5*d,e.font=d+"px Dimbo";return e};
ButtonPanel.prototype.createStats=function(a,b,c,d){for(var e=0,g=0;g<this._stats.length;g++)e+=this._stats[g].amount;g=this.createStatBar(b.height);g.x=b.x;g.y=b.y;this.animateStatBar(g,b.width,c,e,this._initialized);var f=this.createStatLabel(a.width,a.height,c);f.x=b.x+b.width*c/e;f.y=b.y;this.animateStatLabel(f,this._initialized);a.addChild(g,f);d&&(c=this.createSelectedHighlight(b.width,b.height),c.x=b.x,c.y=b.y,a.addChild(c))};
ButtonPanel.prototype.createStatBar=function(a){var b=new createjs.Shape;b.graphics.beginFill("#000").drawRect(0,0,0,a);b.alpha=.5;return b};ButtonPanel.prototype.animateStatBar=function(a,b,c,d,e){createjs.Tween.get(a.graphics.command,{loop:!1}).wait(e?0:1E3).to({w:b*c/d},e?0:2E3,createjs.Ease.getPowInOut(2))};
ButtonPanel.prototype.createStatLabel=function(a,b,c){a=Math.floor(Math.max(a/40,b/30));c=new createjs.Text(c.toString());c.font=a+"px Dimbo";c.color="#000";c.textAlign="left";c.textBaseline="top";c.alpha=0;return c};ButtonPanel.prototype.animateStatLabel=function(a,b){createjs.Tween.get(a,{loop:!1}).wait(b?0:2700).to({alpha:.8},b?0:1E3,createjs.Ease.getPowInOut(2))};
ButtonPanel.prototype.createSelectedHighlight=function(a,b){var c=new createjs.Shape;c.graphics.setStrokeStyle(6).beginStroke("black").drawRect(0,0,a,b);c.alpha=.9;return c};var CatchField=function(a,b,c){this._wordPool=a;this._velocity=1E4/b;this._hitTest=c;this._running=!1;this._interval=6E3/b;this._dummy=new createjs.Shape;this._dummy.persistant=!0;this._apples=[]};
CatchField.prototype.addTo=function(a){a.name="CatchField";this._container=a;if(this._running)for(var b=this._apples,c=0;c<b.length;c++){var d=b[c];d.x*=a.width/this._width;a.addChild(d)}else this._running=!0,this.tick(this._dummy);this._width=a.width;a.addChild(this._dummy)};
CatchField.prototype.tick=function(a){createjs.Tween.get(a,{loop:!0}).wait(this._interval).call(function(){var a=this._container,c=this.createApple(this.getRandomWord(),a.width,Math.max(a.width,a.height));this.animateApple(a,c,.85*a.height-this._appleSize/2,this._velocity);this._apples.push(c);a.addChild(c)}.bind(this))};
CatchField.prototype.createApple=function(a,b,c){this._appleSize=c/6;var d=new createjs.Container;d.addChild(this.createAppleSprite(this._appleSize));d.addChild(this.createAppleLabel(c/12,a));d.x=this.getRandomNumber(this._appleSize/2,b-this._appleSize/2);d.y=-this._appleSize;d.width=this._appleSize;d.text=a.toString();return d};CatchField.prototype.getRandomNumber=function(a,b){return Math.floor(Math.random()*(b-a+1)+a)};
CatchField.prototype.getRandomWord=function(){return this._wordPool[this.getRandomNumber(0,this._wordPool.length-1)]};
CatchField.prototype.animateApple=function(a,b,c,d){b.persistant=!0;createjs.Tween.get(b,{loop:!1}).to({y:c},d).call(function(c){this._hitTest(b)?createjs.Tween.get(b,{loop:!1}).to({rotation:360,alpha:0,scaleX:0,scaleY:0,y:b.y+this._appleSize/2},500).call(function(c){this._apples.splice(this._apples.indexOf(b),1);a.removeChild(b)}.bind(this)):createjs.Tween.get(b,{loop:!1}).to({y:b.y+a.height},d).call(function(c){this._apples.splice(this._apples.indexOf(b),1);a.removeChild(b)}.bind(this))}.bind(this))};
CatchField.prototype.createAppleSprite=function(a){var b=new createjs.Bitmap("img/apple.png");b.image.onload=function(){b.scaleX=b.scaleY=a/b.image.width};b.x-=this._appleSize/2;b.y-=this._appleSize/2;return b};CatchField.prototype.createAppleLabel=function(a,b){var c=.5*a,d=new createjs.Text;d.text=b.toString();d.font=c+"px Dimbo";d.color="#d3d3d3";d.lineWidth=this._appleSize;d.textAlign="center";d.textBaseline="middle";return d};var CorrectWrongDisplay=function(a){this._answers=a};
CorrectWrongDisplay.prototype.addTo=function(a){a.name="CorrectWrongDisplay";var b=this.createWordList(this._answers.correct,!0,a.width,a.height);b.y=.5*a.height;var c=this.createWordList(this._answers.wrong,!1,a.width,a.height);c.y=.7*a.height;var d=this.createBackgroundPanel(.95*a.width,.4*a.height);d.x+=.5*a.width;d.y+=.65*a.height;a.addChild(d,b,c)};
CorrectWrongDisplay.prototype.createWordList=function(a,b,c,d){d=Math.floor(Math.max(c/30,d/25));var e=new createjs.Text;e.font=d+"px Dimbo";e.lineWidth=.9*c;e.lineHeight=1.1*d;e.textAlign="left";e.textBaseline="middle";e.x=.05*c;b?(e.text="Correct: "+this.concatenateWords(a),e.color="green"):(e.text="Wrong: "+this.concatenateWords(a),e.color="#f0261b");return e};
CorrectWrongDisplay.prototype.createBackgroundPanel=function(a,b){var c=new createjs.Container,d=new createjs.Shape;d.graphics.beginFill("#d3d3d3").drawRect(0,0,a,b);d.x=-a/2;d.y=-b/2;var e=this.createDivisorLine(a);c.addChild(d,e);return c};CorrectWrongDisplay.prototype.createDivisorLine=function(a){var b=new createjs.Shape;b.graphics.setStrokeStyle(3).beginStroke("black").moveTo(-a/2,0).lineTo(a/2,0).endStroke();b.alpha=.5;return b};
CorrectWrongDisplay.prototype.concatenateWords=function(a){for(var b="",c=0;c<a.length;c++)0<c&&(b+=", "),b+=a[c];return b};var DifficultyMeter=function(a){this._numStars=5;this._value=Math.min(a,this._numStars)};DifficultyMeter.prototype.addTo=function(a){a.name="DifficultyMeter";if(!(0>this._value))for(var b=0;b<this._numStars;b++){var c=this.createStar(a.width,a.height,b);a.addChild(c)}};
DifficultyMeter.prototype.createStar=function(a,b,c){var d=Math.max(a/80,b/60);a=Math.max(a/30,b/25);b=new createjs.Shape;c<this._value?b.graphics.beginFill("#F0261B"):b.graphics.beginFill("#333333");b.graphics.drawPolyStar(0,0,d,5,.6,-90);b.x=-((this._numStars/2-c)*a)+a/2;b.y=0;return b};var DisplayImage=function(a){this._imagePath=a};DisplayImage.prototype.addTo=function(a){a.name="DisplayImage";var b=this.createImageObject(a.width,a.height,this._imagePath);a.addChild(b)};
DisplayImage.prototype.createImageObject=function(a,b,c){var d=new createjs.Bitmap(c),e=a>=b;d.image.onload=function(){var c=Math.min(.4*a/d.image.width,.5*b/d.image.height);e||(c*=.9);d.scaleX=d.scaleY=c;d.x=-(d.image.width*d.scaleX)/2;d.y=-(d.image.height*d.scaleY)/2};d.shadow=new createjs.Shadow("#333333",5,5,10);return d};
var FireworkEffect=function(){this._sprite=new createjs.Sprite(new createjs.SpriteSheet({images:["img/spritesheet_sparkle.png"],frames:{width:200,height:200,regX:100,regY:100}}));this._sparkles=[]};FireworkEffect.prototype.addTo=function(a){this._container=a;for(a=0;a<this._sparkles.length;a++)this.tick(this._sparkles[a])};
FireworkEffect.prototype.tick=function(a){0>this._container.getChildIndex(a)&&this._container.addChild(a);for(var b=a.numChildren,c=b-1;0<=c;c--){var d=a.getChildAt(c);d.vY+=.8;d.vX*=.99;d.x+=1*d.vX;d.y+=1*d.vY;d.scaleX=d.scaleY=d.scaleX+1*d.vS;d.alpha+=1*d.vA;(0>=d.alpha||d.y>this._container.height)&&a.removeChild(d)}0==b?(this._container.removeChild(a),this._sparkles.splice(this._sparkles.indexOf(a),1)):createjs.Tween.get(this._container).wait(createjs.Ticker.interval).call(this.tick.bind(this),
[a])};
FireworkEffect.prototype.explosionAnimation=function(a,b,c,d){for(var e=new createjs.Container,g=this._container.width,f=this._container.height,k=0;k<a;k++){var l=this._sprite.clone();l.x=b;l.y=c;l.rotation=360*Math.random();l.alpha=.5*Math.random()+.5;var m=Math.min(g/1E3,f/1E3);l.scaleX=l.scaleY=Math.random()*m+m;var m=2*Math.PI*Math.random(),h=30*(Math.random()-.5)*d;l.vX=Math.cos(m)*h;l.vY=Math.sin(m)*h;l.vS=.2*(Math.random()-.5);l.vA=.02*-Math.random()-.01;l.gotoAndPlay(Math.random()*l.spriteSheet.getNumFrames());e.addChild(l)}this._sparkles.push(e);
this._running||this.tick(e)};var FooterTextDisplay=function(a){this._value=a};FooterTextDisplay.prototype.addTo=function(a){a.name="FooterTextDisplay";this._label=this.createLabel(a.width,a.height);a.addChild(this._label)};FooterTextDisplay.prototype.createLabel=function(a,b){var c=Math.floor(Math.max(a/40,b/30)),d=new createjs.Text;d.text=this._value.toString();d.font=c+"px Dimbo";d.color="#f0261b";d.textAlign="center";d.textBaseline="bottom";return d};
FooterTextDisplay.prototype.update=function(a){this._value=a;this._label.text=a.toString()};var HeaderDisplay=function(a){this._value=a};HeaderDisplay.prototype.addTo=function(a){a.name="HeaderDisplay";var b=this.createLabel(a.width,a.height,this._value),c=this.createBackgroundPanel(b.getMeasuredWidth(),b.getMeasuredHeight());a.addChild(c,b)};
HeaderDisplay.prototype.createLabel=function(a,b,c){a=Math.floor(Math.max(a/23,b/20));b=new createjs.Text;b.text=c.toString();b.font=a+"px Dimbo";b.color="#f0261b";b.textAlign="left";b.textBaseline="top";return b};HeaderDisplay.prototype.createBackgroundPanel=function(a,b){var c=new createjs.Shape;c.graphics.beginFill("#d3d3d3").drawRoundRectComplex(0,0,a+b/2,1.5*b,0,0,b,0);return c};var HighscoreList=function(a){this._ranklist=a};
HighscoreList.prototype.addTo=function(a){this._container=a;a.name="HighscoreList";for(var b=.9*a.width,c=a.height/9,d=0;d<this._ranklist.length;d++){var e=-b/2,g=c*d,f=this._ranklist[d],k=Math.min(.8*a.width,.8*a.height)/(9*window.devicePixelRatio),l=k-k/5*Math.min(d,2.5),k=l/80*c,m=this.createBackgroundPanel(b,c,d);m.x=e;m.y=g;var h=this.createRankLabel(l,d);h.x=e+.15*b;h.y=g+c/2;var p=this.createNameLabel(l,f.name);p.x=e+.2*b;p.y=g+c/2;var q=this.createScoreLabel(l,f.score);q.x=e+.7*b;q.y=g+c/
2;var n=this.createChangeIcon(k,f.change);n.x=e+.85*b;n.y=g+c/2;f=this.createChangeLabel(l,f.change);f.x=e+.93*b;f.y=g+c/2;a.addChild(m,h,p,q,f);0==d&&(f=this.createCrownIcon(k),f.x+=e+.06*b,f.y+=g+c/2)}};
HighscoreList.prototype.createBackgroundPanel=function(a,b,c){var d=new createjs.Shape;d.graphics.beginFill("#d3d3d3").drawRect(0,0,a,b);d.shadow=new createjs.Shadow("#333333",5,5,10);switch(c){case 0:d.filters=[new createjs.ColorFilter(1,1,1,1,75,75,10,0)];break;case 1:d.filters=[new createjs.ColorFilter(1,1,1,1,30,30,10,0)];break;case 2:d.filters=[new createjs.ColorFilter(1,1,1,1,15,15,10,0)];break;case 3:d.filters=[new createjs.ColorFilter(1,1,1,1,7,7,4,0)]}d.cache(0,0,a,b);return d};
HighscoreList.prototype.createCrownIcon=function(a){var b=new createjs.Bitmap("img/crown.jpg");b.image.onload=function(){var c=a/b.image.height;b.scaleX=b.scaleY=c;b.x-=b.image.width*c/2;b.y-=b.image.height*c/2;this._container.addChild(b)}.bind(this);return b};HighscoreList.prototype.createRankLabel=function(a,b){var c=new createjs.Text;c.text=b+1+" .";c.font=a+"px Dimbo";c.color="#f0261b";c.textAlign="center";c.textBaseline="middle";return c};
HighscoreList.prototype.createNameLabel=function(a,b){var c=new createjs.Text;c.text=b.toString();c.font=a+"px Dimbo";c.color="#f0261b";c.textAlign="left";c.textBaseline="middle";return c};HighscoreList.prototype.createScoreLabel=function(a,b){var c=new createjs.Text;c.text=b.toString();c.font=a+"px Dimbo";c.color="#f0261b";c.textAlign="center";c.textBaseline="middle";return c};
HighscoreList.prototype.createChangeIcon=function(a,b){var c;c=0<b?new createjs.Bitmap("img/rankUp.png"):0>b?new createjs.Bitmap("img/rankDown.png"):new createjs.Bitmap("img/rankSame.png");c.image.onload=function(){var b=a/c.image.height;c.scaleX=c.scaleY=b;c.x-=c.image.width*b/2;c.y-=c.image.height*b/2;this._container.addChild(c)}.bind(this);return c};
HighscoreList.prototype.createChangeLabel=function(a,b){var c=new createjs.Text;0<b&&(b="+"+b.toString());0==b&&(b="-");c.text=b;c.font=a+"px Dimbo";c.color=0<b?"#3bb742":0>b?"#f0261b":"#496da3";c.textAlign="center";c.textBaseline="middle";return c};HighscoreList.prototype.update=function(a){this._ranklist=a;this._container.removeAllChildren();this.addTo(this._container)};var InteractiveImage=function(a,b,c){this._imagePath=a;this._submit=b;this._stats=c;this._initialized=!1};
InteractiveImage.prototype.addTo=function(a){this._container=a;a.name="InteractiveImage";this.createInteractiveImage(a);this.preloadPinIcon()};
InteractiveImage.prototype.createInteractiveImage=function(a){var b=new createjs.Bitmap(this._imagePath),c=a.width/20;b.image.onload=function(){b.scaleX=b.scaleY=Math.min(.9*a.width/b.image.width,(a.height/2+c)/b.image.height);b.x=-(b.image.width*b.scaleX)/2;b.y=-(b.image.height*b.scaleY)/2;this._container.addChild(b);void 0!=this._stats&&(this.createStats(this._stats,b),this._initialized=!0)}.bind(this);b.shadow=new createjs.Shadow("#333333",5,5,10);b.on("click",function(c){if(null!=this._submit||
c.isAnswer){var e=this.createPin(a.width,a.height);e.x=c.localX*b.scaleX+b.x;e.y=c.localY*b.scaleY+b.y;c.selected&&(e.filters=[new createjs.ColorFilter(0,0,0,1,255,99,71,0)]);if(c.isAnswer){e.alpha=0;var g=e.x,f=e.y;e.x+=50;e.y-=50;e.alpha=0;var k=Math.round(300*Math.random());this._initialized||(k+=1E3);createjs.Tween.get(e,{loop:!1}).wait(k).to({x:g,y:f,alpha:1},300,createjs.Ease.getPowInOut(2))}null!=this._submit&&this._submit([Math.round(c.localX),Math.round(c.localY)])}}.bind(this));return b};
InteractiveImage.prototype.createPin=function(a,b){var c=new createjs.Bitmap("img/pin.png");c.image.onload=function(){var d=Math.min(.05*a/c.image.width,.05*b/c.image.height);c.scaleX=c.scaleY=d;c.y-=c.image.height*d;c.cache(0,0,c.image.width,c.image.height);this._container.addChild(c)}.bind(this);return c};InteractiveImage.prototype.preloadPinIcon=function(){(new createjs.LoadQueue).loadFile("img/pin.png")};
InteractiveImage.prototype.createStats=function(a,b){var c=a.correct;this.createCorrectArea(c.type,c.data,b);for(var c=a.answers,d=0;d<c.length;d++){var e=new createjs.Event("click");e.localX=c[d].x;e.localY=c[d].y;e.selected=c[d].selected;e.isAnswer=!0;b.dispatchEvent(e)}};
InteractiveImage.prototype.createCorrectArea=function(a,b,c){var d=new createjs.Shape;switch(a){case "polygon":d.graphics.beginFill("green");d.graphics.moveTo(this.convertLocalToAbsoluteX(b[0].x,c),this.convertLocalToAbsoluteY(b[0].y,c));for(a=1;a<b.length;a++)d.graphics.lineTo(this.convertLocalToAbsoluteX(b[a].x,c),this.convertLocalToAbsoluteY(b[a].y,c));d.graphics.lineTo(this.convertLocalToAbsoluteX(b[b.length-1].x,c),this.convertLocalToAbsoluteY(b[b.length-1].y,c));d.graphics.endFill();break;case "circle":a=
Math.round(Math.sqrt(Math.pow(b.center.x-b.radius.x,2)+Math.pow(b.center.y-b.radius.y,2))*c.scaleX),d.graphics.beginFill("green").drawCircle(this.convertLocalToAbsoluteX(b.center.x,c),this.convertLocalToAbsoluteY(b.center.y,c),a)}d.alpha=.7;this._container.addChild(d)};InteractiveImage.prototype.convertLocalToAbsoluteX=function(a,b){return a*b.scaleX+b.x};InteractiveImage.prototype.convertLocalToAbsoluteY=function(a,b){return a*b.scaleY+b.y};
var LabelIterator=function(a,b,c){this._values=a;this._interval=Math.max(b,0);this.onChange=c;this._currentIndex=0;this._running=!1};LabelIterator.prototype.addTo=function(a){a.name="LabelIterator";this._label=this.createLabel(a.width,a.height);this._running?(this.updateLabel(),this.updateColor()):(this._running=!0,this.tick());a.addChild(this._label)};
LabelIterator.prototype.createLabel=function(a,b){var c=Math.floor(Math.max(a/20,b/20)),d=new createjs.Text;d.font=c+"px Dimbo";d.color="#000";d.textAlign="center";d.textBaseline="middle";return d};LabelIterator.prototype.updateLabel=function(){this._label.text=this._values[this._currentIndex]};
LabelIterator.prototype.tick=function(){this.updateLabel();this.updateColor();this._label.persistant=!0;createjs.Tween.get(this._label,{loop:!1}).wait(this._interval).call(function(){this._currentIndex=(this._currentIndex+1)%this._values.length;this.tick()}.bind(this))};LabelIterator.prototype.updateColor=function(){null!=this.onChange&&(this.onChange(this._values[this._currentIndex])?this._label.color="#f0261b":this._label.color="#000")};var MovingPlatform=function(){this._lastKeyPressed=null};
MovingPlatform.prototype.addTo=function(a){a.name="MovingPlatform";this._width=a.width;this._height=a.height;var b=this.createPlatform2(Math.max(a.width,a.height)/6,a.height/20,"img/basket.png");b.x+=.5*a.width;b.y+=.85*a.height;this._platform=b;this.createPlatformControls(b,a);a.addChild(b)};MovingPlatform.prototype.createPlatform=function(a,b){var c=new createjs.Shape;c.graphics.beginFill("#d3d3d3").drawRect(0,0,a,b);c.width=a;c.height=b;return c};
MovingPlatform.prototype.createPlatform2=function(a,b,c){var d=new createjs.Bitmap(c);d.image.onload=function(){d.scaleX=d.scaleY=a/d.image.width;d.x-=d.image.width*d.scaleX/2;d.regX=d.image.width/2};d.width=a;d.height=b;return d};
MovingPlatform.prototype.createPlatformControls=function(a,b){window.onkeydown=function(b){this._lastKeyPressed=b=b.key;"a"===b||"A"===b||"ArrowLeft"===b||"Left"===b?this.movePlatform(a,0):"d"!==b&&"D"!==b&&"ArrowRight"!==b&&"Right"!==b||this.movePlatform(a,this._width)}.bind(this);window.onkeyup=function(b){this._lastKeyPressed===b.key&&this.stopPlatform(a)}.bind(this);this.createHitArea(b);b.on("mousedown",function(b){this._lastKeyPressed="MouseClick";this.movePlatform(a,b.rawX)}.bind(this));b.on("pressmove",
function(b){this._lastKeyPressed="MouseClick";this.movePlatform(a,b.rawX)}.bind(this));b.on("pressup",function(b){"MouseClick"===this._lastKeyPressed&&this.stopPlatform(a)}.bind(this))};MovingPlatform.prototype.createHitArea=function(a){var b=new createjs.Shape;b.graphics.beginFill("#000").drawRect(0,0,a.width,a.height);a.hitArea=b};
MovingPlatform.prototype.movePlatform=function(a,b){b=Math.max(Math.min(b,this._width-a.width/2),a.width/2);a.x>b?(0<a.scaleX&&(a.scaleX*=-1),createjs.Tween.get(a,{loop:!1,override:!0}).to({x:b},1500*(a.x-b)/this._width,createjs.Ease.getPowInOut(1))):a.x<b&&(0>a.scaleX&&(a.scaleX*=-1),createjs.Tween.get(a,{loop:!1,override:!0}).to({x:b},1500*(b-a.x)/this._width,createjs.Ease.getPowInOut(1)))};MovingPlatform.prototype.stopPlatform=function(a){createjs.Tween.removeTweens(a)};
MovingPlatform.prototype.hitTestBetween=function(a,b){return this.hitTest(a)||this.hitTest(b)||a<this._platform.x&&b>this._platform.x+this._platform.width?!0:!1};MovingPlatform.prototype.hitTest=function(a){return Math.abs(this._platform.x-a)<=this._platform.width/2?!0:!1};
var RaceProgressionDisplay=function(a,b){this._spriteWidth=400;this._spriteHeight=248;this._sprite=new createjs.Sprite(new createjs.SpriteSheet({images:["img/spritesheet_horse.png"],frames:{width:this._spriteWidth,height:this._spriteHeight,regX:Math.round(this._spriteWidth/2),regY:Math.round(this._spriteHeight/2)}}));this._sprite.gotoAndStop(7);this._groups=a;this._numSteps=b};
RaceProgressionDisplay.prototype.addTo=function(a){this._container=a;a.name="RaceProgressionDisplay";var b=this._groups.length,c=.7*a.width,d=a.height/(2*b),e=a.width/10;this._stepWidth=c/this._numSteps;this._horseSprites=[];this._rankCounter=1;for(var g=0;g<b;g++){var f=this.createLabel(this._groups[g].name,c);f.x=-c/2+.9*e;f.y=d*(g+.5);var k=this.createProgressBar(this._groups[g].position,this._numSteps,this._groups[g].color,c,d);k.x=-c/2+e;k.y=d*g;a.addChild(k,f)}for(g=1;g<this._numSteps;g++)a.addChild(this.createStepDivisor(-c/
2+e+g*this._stepWidth,d*b));for(g=0;g<b;g++)f=this.createHorseSprite(),f.x=-c/2+this._groups[g].position*this._stepWidth+this._stepWidth/2+e,f.y=d*(g+.5),f.scaleX=f.scaleY=3*d/5/this._spriteHeight,f.position=this._groups[g].position,a.addChild(f),this._horseSprites[this._groups[g].name]=f,f.position>=this._numSteps-1&&this.createRankLabel(g)};
RaceProgressionDisplay.prototype.createStepDivisor=function(a,b){var c=new createjs.Shape;c.graphics.setStrokeStyle(3).beginStroke("black").moveTo(a,0).lineTo(a,b).endStroke();c.alpha=.5;return c};RaceProgressionDisplay.prototype.createLabel=function(a,b){var c=b/20,d=new createjs.Text;d.text=a.toString();d.font=c+"px Dimbo";d.color="#000";d.textAlign="right";d.textBaseline="middle";return d};
RaceProgressionDisplay.prototype.createProgressBar=function(a,b,c,d,e){a=new createjs.Shape;a.graphics.beginFill(c).drawRect(0,0,d,e);a.shadow=new createjs.Shadow("#333333",5,5,10);return a};RaceProgressionDisplay.prototype.createHorseSprite=function(){return this._sprite.clone()};
RaceProgressionDisplay.prototype.update=function(a,b){var c=this._horseSprites[a];if(!c)return console.log("Group "+a+" not found."),!1;if(0<=c.position+b&&c.position<this._numSteps-1){var d=c.position;c.position=Math.max(Math.min(c.position+b,this._numSteps-1),0);d=c.position-d;createjs.Tween.get(c,{loop:!1}).to({scaleX:0>d?-c.scaleX/2:c.scaleX},0>d?200:0).to({scaleX:0>d?-c.scaleX:c.scaleX},0>d?200:0).call(c.play).to({x:c.x+d*this._stepWidth},1E3*Math.abs(d)).call(c.gotoAndStop,[7]).to({scaleX:c.scaleX},
0>d?200:0);for(c=this._groups.length-1;0<=c;c--)if(this._groups[c].name===a){this._groups[c].position+=d;this._groups[c].position==this._numSteps-1&&this.createRankLabel(c);break}return!0}return!1};
RaceProgressionDisplay.prototype.createRankLabel=function(a){var b;this._groups[a].rank?(b=this._groups[a].rank,this._rankCounter=Math.max(this._rankCounter,b)):(b=this._rankCounter,this._groups[a].rank=b);var c=this._container.width/30,d=new createjs.Text;d.text=b.toString()+". ";d.font=c+"px Dimbo";d.color="#f0261b";d.textAlign="right";d.textBaseline="middle";d.x=this._container.width/2;d.y=this._container.height/(2*this._groups.length)*(a+.5);this._rankCounter++;this._container.addChild(d)};
var RoundButton=function(a,b){this._value=a;this._action=b};RoundButton.prototype.addTo=function(a){a.name="RoundButton";var b=Math.min(a.width/4,a.height/5),c=this.createLabel(a.width,a.height,this._value),b=this.createBackgroundCircle(b);a.addChild(b,c)};RoundButton.prototype.createLabel=function(a,b,c){a=Math.floor(Math.min(a/10,b/10));b=new createjs.Text;b.text=c.toString();b.font="bold "+a+"px Dimbo";b.color="#d3d3d3";b.textBaseline="middle";b.textAlign="center";return b};
RoundButton.prototype.createBackgroundCircle=function(a){function b(b){switch(b.type){case "mouseover":b.target.filters=[new createjs.ColorFilter(1,1,1,1,-25,-25,-25,0)];break;case "mouseout":b.target.filters=[new createjs.ColorFilter(1,1,1,1,0,0,0,0)]}b.target.cache(-a,-a,2*a,2*a)}var c=new createjs.Shape;c.graphics.beginRadialGradientFill(["#F0261B","#C01E15"],[0,1],0,0,0,0,0,a).drawCircle(0,0,a);c.shadow=new createjs.Shadow("#000000",5,5,10);c.on("click",function(b){null!=this._action&&(b.target.filters=
[new createjs.ColorFilter(0,0,0,1,144,22,16,0)],b.target.cache(-a,-a,2*a,2*a),setTimeout(function(){b.target.filters=void 0;b.target.uncache()},150),this._action())}.bind(this));c.on("mouseover",b.bind(this));c.on("mouseout",b.bind(this));return c};var SubmitButton=function(a){this._submit=a};SubmitButton.prototype.addTo=function(a){a.name="SubmitButton";var b=this.createLabel(a.width,a.height),c=this.createBackgroundPanel(b.getMeasuredWidth(),b.getMeasuredHeight());a.addChild(c,b)};
SubmitButton.prototype.createLabel=function(a,b){var c=Math.floor(Math.max(a/23,b/20)),d=new createjs.Text;d.text="Submit";d.font=c+"px Dimbo";d.color="#f0261b";d.textAlign="right";d.textBaseline="bottom";return d};
SubmitButton.prototype.createBackgroundPanel=function(a,b){function c(a){switch(a.type){case "mouseover":a.target.filters=[new createjs.ColorFilter(1,1,1,1,-25,-25,-25,0)];break;case "mouseout":a.target.filters=[new createjs.ColorFilter(1,1,1,1,0,0,0,0)]}a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h)}var d=a+b/2,e=1.5*b,g=new createjs.Shape;g.graphics.beginFill("#d3d3d3").drawRoundRectComplex(0,0,d,e,b,0,0,0);g.x=-d;g.y=-e;g.on("click",function(a){null!=this._submit&&
(a.target.filters=[new createjs.ColorFilter(0,0,0,1,255,203,151,0)],a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h),this._submit())}.bind(this));g.on("mouseover",c.bind(this));g.on("mouseout",c.bind(this));return g};var TextBox=function(a){this._submit=a};TextBox.prototype.addTo=function(a){a.name="TextBox";this._textBox||(this._textBox=this.createTextBox(a.width));this._textBox.x=-this._textBox.htmlElement.offsetWidth/2;a.addChild(this._textBox)};
TextBox.prototype.createTextBox=function(a){var b=document.createElement("template");b.innerHTML='<div class="form-group" id="textBox" style="width:60%; top:'+document.getElementById("header").offsetHeight+'px; left:0"><input class="form-control input-lg" type="text" placeholder="Enter suggestion"></div>';b=b.content.firstChild;$("#placeholder").append(b);b.addEventListener("keydown",function(a){13==a.keyCode&&(a=b.getElementsByTagName("input")[0],a.value&&(this._submit(a.value),a.value="",a=document.createElement("template"),
a.innerHTML='<label id="submitInfoLabel" style="position:absolute; top:-30px; left:0; color:#f0261b;">Submitted!</label>',a=a.content.firstChild,$("#textBox").prepend(a),$("#submitInfoLabel").hide(),$("#submitInfoLabel").show("drop",{},500,function(){setTimeout(function(){$("#submitInfoLabel").fadeOut();setTimeout(function(){$("#submitInfoLabel").remove()},500)},1500)})))}.bind(this));return new createjs.DOMElement(b)};
var TimeDisplay=function(a,b){this._currentTime=this._totalTime=Math.max(Math.round(a),0);this._tickTime=1E3;this._running=!1;this._submit=b;this._initialized=!1};
TimeDisplay.prototype.addTo=function(a){this._container=a;a.name="TimeDisplay";if(0<this._currentTime||!this._submit)this._radius=Math.max(a.width/9,a.height/7),this._backgroundCircle=this.createBackgroundCircle(),this._timeLabel=this.createTimeLabel(a.width,a.height,this._currentTime),this._progressArc=this.createProgressArc(a.width,a.height),this.updateProgressAnimation(),this._running&&this.startProgressAnimation(),a.addChild(this._backgroundCircle,this._progressArc,this._timeLabel),this._initialized||
(this.startTimer(!0),this._initialized=!0)};TimeDisplay.prototype.createBackgroundCircle=function(){var a=new createjs.Shape;a.graphics.beginFill("#d3d3d3").drawCircle(0,0,this._radius);a.filters=[new createjs.ColorFilter(1,1,1,1)];return a};
TimeDisplay.prototype.createTimeLabel=function(a,b,c){a=Math.floor(Math.max(a/18,b/15));b=new createjs.Text;b.text=c.toString();b.font=a+"px Dimbo";b.color="#F0261B";b.x=.4*-this._radius;b.y=.4*this._radius;b.lineWidth=this._radius;b.textAlign="center";b.textBaseline="middle";return b};
TimeDisplay.prototype.createProgressArc=function(a,b){var c=Math.max(a/80,b/60),d=new createjs.Shape;d.graphics.setStrokeStyle(c).beginStroke("#F0261B").arc(0,0,this._radius,Math.PI/2,Math.PI);d.x=d.regX=0;d.y=d.regY=0;return d};TimeDisplay.prototype.startTimer=function(a){this._running||(this._running=!0,this.startProgressAnimation(),this.tick(new Date((new Date).getTime()-this._tickTime)),a||this.statusAnimation("resumed"))};
TimeDisplay.prototype.stopTimer=function(){this._running&&(this._running=!1,this.stopProgressAnimation(),this.updateProgressAnimation(),this.statusAnimation("paused"))};
TimeDisplay.prototype.tick=function(a){if(0<this._currentTime){this._lastSleepTime||(this._lastSleepTime=this._tickTime);var b=this._tickTime-((new Date).getTime()-a.getTime()-this._lastSleepTime);this._lastSleepTime=b;a=new Date;this._timeLabel.persistant=!0;createjs.Tween.get(this._timeLabel,{loop:!1}).wait(b).call(function(){this._running&&(0<this._currentTime&&(this._currentTime--,this.updateTimeLabel()),6>this._currentTime&&this.lowTimeAnimation(),this.tick(a))}.bind(this))}else this._running=
!1,null!=this._submit&&this._submit()};TimeDisplay.prototype.updateTimeLabel=function(){this._timeLabel.text=this._currentTime.toString()};TimeDisplay.prototype.changeTime=function(a){this.updateTime(this._currentTime+a)};
TimeDisplay.prototype.updateTime=function(a){var b=this._currentTime;this._currentTime=Math.max(Math.floor(a),0);this._currentTime>this._totalTime&&(this._totalTime=this._currentTime);this.updateTimeLabel();this.updateProgressAnimation();this._running&&this.startProgressAnimation();a=this._currentTime-b;this.statusAnimation(0<=a?"+"+a.toString():a.toString())};
TimeDisplay.prototype.startProgressAnimation=function(){createjs.Tween.get(this._progressArc,{loop:!1,override:!0}).to({rotation:-90},1E3*this._currentTime,createjs.Ease.getPowInOut(1))};TimeDisplay.prototype.stopProgressAnimation=function(){createjs.Tween.removeTweens(this._progressArc)};TimeDisplay.prototype.updateProgressAnimation=function(){this._progressArc.rotation=-90*(1+-this._currentTime/this._totalTime)};
TimeDisplay.prototype.lowTimeAnimation=function(){this._backgroundCircle.cache(-this._radius,0,this._radius,this._radius,2);this._backgroundCircle.handleEvent=function(){this.updateCache()};createjs.Tween.get(this._backgroundCircle.filters[0],{loop:!1}).call(function(a){createjs.Ticker.addEventListener("tick",a)},[this._backgroundCircle]).to({redMultiplier:1.5,greenMultiplier:.3,blueMultiplier:.3},250).to({redMultiplier:1,greenMultiplier:1,blueMultiplier:1},250).call(function(a){createjs.Ticker.removeEventListener("tick",
a)},[this._backgroundCircle])};
TimeDisplay.prototype.statusAnimation=function(a){var b=Math.floor(Math.max(this._container.width/25,this._container.height/25)),c=new createjs.Text;c.text=a.toString();c.font=b+"px Dimbo";c.color="#F0261B";c.x=-this._radius/2;c.y=this._radius;c.alpha=0;c.lineWidth=this._radius;c.textAlign="center";c.textBaseline="bottom";createjs.Tween.get(c,{loop:!1}).to({alpha:1},1E3,createjs.Ease.getPowInOut(1)).to({alpha:0},1E3,createjs.Ease.getPowInOut(1));createjs.Tween.get(c,{loop:!1}).to({y:0},2200,createjs.Ease.getPowInOut(2)).call(function(a,
b){a.removeChild(b)},[this._container,c]);this._container.addChild(c)};TimeDisplay.prototype.getTime=function(){return this._currentTime};var TitleDisplay=function(a){this._value=a};TitleDisplay.prototype.addTo=function(a){a.name="TitleDisplay";var b=.75*a.width,c=a.height/13,d=this.createLabel(b,c),b=this.createBackgroundPanel(b,c,d.getMeasuredHeight());a.addChild(b,d)};
TitleDisplay.prototype.createLabel=function(a,b){var c=Math.floor(Math.max(a/22+5,b/4+30)),d=new createjs.Text;d.text=this._value.toString();d.font=c+"px Dimbo";d.color="#f0261b";d.lineWidth=a-a/15;d.lineHeight=b;d.textAlign="center";for(d.textBaseline="middle";d.getMeasuredHeight()>2*b;)c-=2,d.font=c+"px Dimbo";return d};TitleDisplay.prototype.createBackgroundPanel=function(a,b,c){c=c/b*b+b/2;var d=new createjs.Shape;d.graphics.beginFill("#d3d3d3").drawRoundRect(0,0,a,c,b/2);d.x=-a/2;d.y=b/4-b;return d};
var TooltipInfo=function(a){this._size=25;this._tooltip=a};TooltipInfo.prototype.addTo=function(a){a.name="TooltipInfo";this._infoIcon||(this._infoIcon=this.createInfoIcon(this._tooltip));a.addChild(this._infoIcon)};
TooltipInfo.prototype.createInfoIcon=function(a){var b=document.createElement("template");b.innerHTML='<img src="img/info.png" width="'+this._size+'px" height="'+this._size+'px" style="position:absolute; top:'+document.getElementById("header").offsetHeight+'px; left:0" rel="tooltip" data-placement="bottom" title="'+a+'" onclick="void(0)" />';b=b.content.firstChild;$("#placeholder").append(b);$(document).ready(function(){$('[rel="tooltip"]').tooltip()});a=new createjs.DOMElement(b);a.x-=this._size;
return a};var WordPairs=function(a,b,c){this._answers=a;this._line=new createjs.Shape;this._connections=new createjs.Shape;this._connectMap={};this._panelDictionary=[];this._onChange=b;this._solution=c;if(void 0!=c)for(var d in c)this._connectMap[d]=c[d].pair;this._initialized=!1};
WordPairs.prototype.addTo=function(a){a.name="WordPairs";this._initialized&&this.redrawConnections();var b=this._answers[0],c=this._answers[1],d=.4*a.height,e=d/b.length,b=this.createWordPanel(e,b,"left");b.x=.1*-a.width;b.y=-d/2;c=this.createWordPanel(e,c,"right");c.x=.1*a.width;c.y=-d/2;this._initialized||(this.redrawConnections(),this._initialized=!0);a.addChild(b,c,this._connections,this._line)};
WordPairs.prototype.createWordPanel=function(a,b,c){for(var d=new createjs.Container,e=0;e<b.length;e++){var g=b[e],f=this.createLabel(a,g,c);f.y+=e*a;var k=a/5,l=f.getMeasuredWidth()+k,m=f.getMeasuredHeight()+k,g=this.createPanel(l,m,k,g,c);g.y+=e*a;d.addChild(g,f)}return d};WordPairs.prototype.createLabel=function(a,b,c){a*=.5;var d=new createjs.Text;d.text=b.toString();d.font=a+"px Dimbo";d.color="#f0261b";d.textAlign="left"===c?"right":"left";d.textBaseline="middle";return d};
WordPairs.prototype.createPanel=function(a,b,c,d,e){function g(a){a.target.filters=[new createjs.ColorFilter(1,1,1,1,-25,-25,-25,0)];a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h);this._hoveredPanel=a.target}function f(a){a.target.filters=[new createjs.ColorFilter(1,1,1,1,0,0,0,0)];a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h);this._hoveredPanel=null}function k(a){this._selectedPanel=a.target}function l(a){var b=this._selectedPanel.connectPoint,
c=this._line,b=this._selectedPanel.localToLocal(b[0],b[1],c);a=c.globalToLocal(a.rawX,a.rawY);c.graphics.clear().setStrokeStyle(3).beginStroke("black").moveTo(b.x,b.y).lineTo(a.x,a.y).endStroke()}function m(a){if(a.isTouch){this._hoveredPanel=null;for(var b in this._panelDictionary){var c=this._panelDictionary[b],d=c.globalToLocal(a.rawX,a.rawY);if(c.hitTest(d.x,d.y)){this._hoveredPanel=c;break}}}if(null!=this._hoveredPanel&&this._hoveredPanel.anchor!=this._selectedPanel.anchor){a="left"===this._selectedPanel.anchor?
this._selectedPanel.text:this._hoveredPanel.text;b="right"===this._selectedPanel.anchor?this._selectedPanel.text:this._hoveredPanel.text;for(var e in this._connectMap)if(this._connectMap[e]===b){delete this._connectMap[e];this.redrawConnections();break}this._connectMap[a]=b;this.redrawConnections()}this._selectedPanel=null;this._line.graphics.clear();this._onChange(this._connectMap)}var h=new createjs.Shape;h.text=d.toString();h.anchor=e;h.graphics.beginFill("#d3d3d3").drawRect(0,0,a,b);h.connectPoint=
"left"===e?[a,b/2]:[0,b/2];h.x="left"===e?-a+c/2:-c/2;h.y=-b/2;void 0!=this._onChange&&(h.on("mouseover",g.bind(this)),h.on("mouseout",f.bind(this)),h.on("mousedown",k.bind(this)),h.on("pressmove",l.bind(this)),h.on("pressup",m.bind(this)));return this._panelDictionary[h.text]=h};
WordPairs.prototype.drawConnection=function(a,b,c){a=this._panelDictionary[a];b=this._panelDictionary[b];var d=this._connections;a=a.localToLocal(a.connectPoint[0],a.connectPoint[1],d);b=b.localToLocal(b.connectPoint[0],b.connectPoint[1],d);d.graphics.setStrokeStyle(3).beginStroke(c).moveTo(a.x,a.y).lineTo(b.x,b.y).endStroke()};
WordPairs.prototype.redrawConnections=function(){this._connections.graphics.clear();for(var a in this._connectMap)void 0==this._solution?this.drawConnection(a,this._connectMap[a],"black"):this._solution[a].selected?this.drawConnection(a,this._connectMap[a],"green"):this.drawConnection(a,this._connectMap[a],"#f0261b")};var GuessTheImage=function(a){this._data=a;this._drawable=[];this._submitted=this._initialized=!1};
GuessTheImage.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/idle.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new TextBox(this.sendAnswer.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),
this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer)}this._initialized=!0};GuessTheImage.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
GuessTheImage.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "TextBox":a.x=.5*b.width/window.devicePixelRatio,a.y=.8*b.height/window.devicePixelRatio}};
GuessTheImage.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};GuessTheImage.prototype.sendAnswer=function(a){this._submitted||(a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"answer" : '+JSON.stringify(a)+"}"),ServerConnection.send(a))};
GuessTheImage.prototype.submit=function(){this._submitted||(this._submitted=!0,StageManager.handleActivityEnd())};var Highscore=function(a){this._data=a;this._drawable=[];this._initialized=!1};
Highscore.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/highscore.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay("Highscore"));this._ranklist=new HighscoreList(this._data.ranklist);this._drawable.push(this._ranklist);this._footerDisplay=this._data.best?new FooterTextDisplay("Best score in last round: "+this._data.best.name+" (+"+this._data.best.difference+")"):new FooterTextDisplay("");this._drawable.push(this._footerDisplay);
this._fireworkEffect=new FireworkEffect;this._drawable.push(this._fireworkEffect);this._initialized=!0};
Highscore.prototype.draw=function(a){this._initialized||(this.init(),setTimeout(function(){this._fireworkEffect.explosionAnimation(50,.2*a.width,.2*a.height,2);this._fireworkEffect.explosionAnimation(50,.5*a.width,.3*a.height,2);this._fireworkEffect.explosionAnimation(50,.8*a.width,.2*a.height,2)}.bind(this),1E3));this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
Highscore.prototype.update=function(a){switch(a.component){case "highscore":this._ranklist.update(a.ranklist);a.best&&this._footerDisplay.update("Best score in last round: "+a.best.name+" (+"+a.best.difference+")");break;default:throw Error();}};Highscore.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "HighscoreList":a.x=b.width/2;a.y=b.height/3;break;case "FooterTextDisplay":a.x=b.width/2,a.y=b.height}};
var Idle=function(a){this._data=a;this._drawable=[];this._initialized=!1};Idle.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/idle.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._initialized=!0};Idle.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
Idle.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2,a.y=b.height/5}};var MultipleChoiceFocus=function(a){this._data=a;this._currentItem=null;this._selected=[];this._drawable=[];this._submitted=this._initialized=!1};
MultipleChoiceFocus.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background3.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._labelIterator=
new LabelIterator(this._data.answers,this._data.interval,this.currentItem.bind(this));this._drawable.push(this._labelIterator);this._drawable.push(new RoundButton("Select !",this.select.bind(this)));this._drawable.push(new SubmitButton(this.submit.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._labelIterator=new LabelIterator(this._data.answers,1500,null),this._drawable.push(this._labelIterator),
this._drawable.push(new RoundButton("Select !",null))}this._initialized=!0};MultipleChoiceFocus.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
MultipleChoiceFocus.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "RoundButton":a.x=b.width/2;a.y=.75*b.height;break;case "LabelIterator":a.x=b.width/2;a.y=.45*b.height;break;case "SubmitButton":a.x=b.width,a.y=b.height}};
MultipleChoiceFocus.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};MultipleChoiceFocus.prototype.currentItem=function(a){this._currentItem=a;return-1<this._selected.indexOf(a)?!0:!1};
MultipleChoiceFocus.prototype.select=function(){var a=this._currentItem,b=this._selected.indexOf(a);-1<b?(this._selected.splice(b,1),this._labelIterator.updateColor(!1)):(this._selected.push(a),this._labelIterator.updateColor(!0))};
MultipleChoiceFocus.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd())}};var MultipleChoiceQuestion=function(a){this._data=a;this._selected=[];this._drawable=[];this._submitted=this._initialized=!1};
MultipleChoiceQuestion.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._data.image&&""!=this._data.image&&(this._hasDisplayImage=!0,this._drawable.push(new DisplayImage(this._data.image)));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));
this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new ButtonPanel(this._data.answers,this._hasDisplayImage,this.selected.bind(this),this._data.stats));this._drawable.push(new SubmitButton(this.submit.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._drawable.push(new ButtonPanel(this._data.answers,
this._hasDisplayImage,null,this._data.stats))}this._initialized=!0};MultipleChoiceQuestion.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
MultipleChoiceQuestion.prototype.setOrigin=function(a,b){var c=b.width>=b.height;switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "ButtonPanel":a.x=b.width/2;this._hasDisplayImage&&c&&(a.x+=b.width/4);a.y=.65*b.height;this._hasDisplayImage&&!c&&(a.y=.75*b.height);break;case "DisplayImage":c?(a.x=
b.width/4,a.y=.65*b.height):(a.x=b.width/2,a.y=.45*b.height);break;case "SubmitButton":a.x=b.width,a.y=b.height}};MultipleChoiceQuestion.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};MultipleChoiceQuestion.prototype.selected=function(a){this._selected=a};
MultipleChoiceQuestion.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd())}};var PointAndClick=function(a){this._data=a;this._selected=[];this._drawable=[];this._submitted=this._initialized=!1};
PointAndClick.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/europe.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new InteractiveImage(this._data.image,
this.selected.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._drawable.push(new InteractiveImage(this._data.image,null))}this._initialized=!0};PointAndClick.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
PointAndClick.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "InteractiveImage":a.x=b.width/2,a.y=.65*b.height}};
PointAndClick.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};PointAndClick.prototype.selected=function(a){this._selected=a;this.submit()};
PointAndClick.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd())}};var PointAndClickSolution=function(a){this._data=a;this._selected=[];this._drawable=[];this._submitted=this._initialized=!1};
PointAndClickSolution.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/europe.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._drawable.push(new InteractiveImage(this._data.image,null,this._data.stats));"student"===this._data.view&&this._drawable.push(new HeaderDisplay("Score: +"+this._data.score));this._initialized=!0};
PointAndClickSolution.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
PointAndClickSolution.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "InteractiveImage":a.x=b.width/2,a.y=.65*b.height}};var QuestionSolution=function(a){this._data=a;this._drawable=[];this._initialized=!1};
QuestionSolution.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._data.image&&""!=this._data.image&&(this._hasDisplayImage=!0,this._drawable.push(new DisplayImage(this._data.image)));this._drawable.push(new ButtonPanel(this._data.answers,this._hasDisplayImage,null,this._data.stats));
"student"===this._data.view&&this._drawable.push(new HeaderDisplay("Score: +"+this._data.score));this._initialized=!0};QuestionSolution.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
QuestionSolution.prototype.setOrigin=function(a,b){var c=b.width>=b.height;switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "ButtonPanel":a.x=b.width/2;this._hasDisplayImage&&c&&(a.x+=b.width/4);a.y=.67*b.height;this._hasDisplayImage&&!c&&(a.y=.8*b.height);break;case "DisplayImage":c?(a.x=b.width/4,a.y=.67*b.height):(a.x=b.width/2,a.y=.46*b.height);break;case "HeaderDisplay":a.x=
0,a.y=0}};var Race=function(a){this._data=a;this._drawable=[];this._initialized=!1};
Race.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/highscore.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay("Race"));this._rpd=new RaceProgressionDisplay(this._data.groups,this._data.steps);this._drawable.push(this._rpd);this._footerDisplay=new FooterTextDisplay("");this._drawable.push(this._footerDisplay);this._fireworkEffect=new FireworkEffect;this._drawable.push(this._fireworkEffect);this._initialized=!0};
Race.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};Race.prototype.update=function(a){switch(a.component){case "rpd":this._rpd.update(a.group,a.value)&&this._footerDisplay.update("Last move: "+a.group+" ("+(0<=a.value?"+"+a.value:a.value)+")");break;default:throw Error();}};
Race.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "RaceProgressionDisplay":a.x=b.width/2;a.y=b.height/3;break;case "FooterTextDisplay":a.x=b.width/2,a.y=b.height}};var SimpleFocus=function(a){this._data=a;this._selected=null;this._drawable=[];this._submitted=this._initialized=!1};
SimpleFocus.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background3.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new LabelIterator(this._data.answers,
this._data.interval,this.selected.bind(this)));this._drawable.push(new RoundButton("Stop !",this.submit.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._drawable.push(new LabelIterator(this._data.answers,1500,null)),this._drawable.push(new RoundButton("Stop !",null))}this._initialized=!0};
SimpleFocus.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
SimpleFocus.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "RoundButton":a.x=b.width/2;a.y=.75*b.height;break;case "LabelIterator":a.x=b.width/2,a.y=.45*b.height}};
SimpleFocus.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};SimpleFocus.prototype.selected=function(a){this._selected=a};
SimpleFocus.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd())}};var SimpleQuestion=function(a){this._data=a;this._selected=[null];this._drawable=[];this._submitted=this._initialized=!1};
SimpleQuestion.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._data.image&&""!=this._data.image&&(this._hasDisplayImage=!0,this._drawable.push(new DisplayImage(this._data.image)));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));
this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new ButtonPanel(this._data.answers,this._hasDisplayImage,this.selected.bind(this),this._data.stats));this._drawable.push(new TooltipInfo("Carefully read the question and click on the right answer."));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._drawable.push(new ButtonPanel(this._data.answers,
this._hasDisplayImage,null,this._data.stats))}this._initialized=!0};SimpleQuestion.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
SimpleQuestion.prototype.setOrigin=function(a,b){var c=b.width>=b.height;switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "ButtonPanel":a.x=b.width/2;this._hasDisplayImage&&c&&(a.x+=b.width/4);a.y=.67*b.height;this._hasDisplayImage&&!c&&(a.y=.8*b.height);break;case "DisplayImage":c?(a.x=b.width/
4,a.y=.67*b.height):(a.x=b.width/2,a.y=.46*b.height);break;case "TooltipInfo":a.x=b.width/window.devicePixelRatio,a.y=0/window.devicePixelRatio}};SimpleQuestion.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};
SimpleQuestion.prototype.selected=function(a){this._selected=a;this.submit()};SimpleQuestion.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected[0])+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd())}};var ServerConnection=function(){};
ServerConnection.send=function(a){console.log("To server: "+JSON.stringify(a));"function"==typeof sendJSON&&sendJSON(a);return!0};ServerConnection.receive=function(a){console.log("From server: "+JSON.stringify(a));MessageInterpreter.interpret(a);return!0};var StageManager=function(){};StageManager.init=function(a){this._canvas=a;this._stage=null;this._tranScreens=new createjs.Container;this._overlay=null;this._height=this._width=0;StageManager.updateSize();this._isInitialized=!0};
StageManager.idle=function(){return StageManager.draw(new Idle(JSON.parse('{ "cmd":"show", "screen": "Idle", "text":"Waiting for an activity...", "bg":"img/idle.jpg" }')))};StageManager.draw=function(a,b){if(!this._isInitialized||null==a)return!1;window.onkeydown=null;window.onkeyup=null;var c=StageManager.createScreenContainer();$("#placeholder").empty();a.draw(c);a.container=c;b?StageManager.addOverlay(a):StageManager.transition(a);return!0};StageManager.update=function(a){try{this._currentScreen.update(a)}catch(b){console.log("Update cannot be applied to the current screen.")}};
StageManager.createStage=function(){var a=new createjs.Stage(this._canvas);a.canvas.width=this._width;a.canvas.height=this._height;a.enableMouseOver(20);createjs.Touch.enable(a);createjs.Ticker.setFPS(30);createjs.Ticker.timingMode=createjs.Ticker.RAF;createjs.Ticker.addEventListener("tick",a);a.addChild(this._tranScreens);return a};StageManager.createScreenContainer=function(){var a=new createjs.Container;a.width=this._width;a.height=this._height;return a};
StageManager.updateSize=function(){var a=document.getElementById("header").offsetHeight,b=document.getElementById("footer").offsetHeight;this._width=window.innerWidth;this._height=window.innerHeight-(a+b);this._width*=window.devicePixelRatio;this._height*=window.devicePixelRatio};
StageManager.resize=function(){if(null==this._stage)return!1;StageManager.updateSize();var a=this._height;this._stage.canvas.width=this._width;this._stage.canvas.height=a;this._stage.update();StageManager.redrawScreen(this._currentScreen);null!=this._overlay&&StageManager.redrawScreen(this._overlay);return!0};StageManager.redrawScreen=function(a){var b=a.container;Common.removeTweens(b,!1);b.removeAllChildren();b.width=this._stage.canvas.width;b.height=this._stage.canvas.height;a.draw(b)};
StageManager.addOverlay=function(a){this._overlay&&StageManager.removeOverlay();this._overlay=a;a.container.scaleX=a.container.scaleY=0;a.container.alpha=.5;this._stage.addChildAt(a.container,1);StageManager.expandOverlay()};StageManager.expandOverlay=function(){null!=this._overlay?createjs.Tween.get(this._overlay.container,{loop:!1,override:!0}).to({scaleX:1,scaleY:1,alpha:1},1E3,createjs.Ease.getPowInOut(2)):console.log("Cannot expand overlay: There is no active overlay.")};
StageManager.minifyOverlay=function(){null!=this._overlay?createjs.Tween.get(this._overlay.container,{loop:!1,override:!0}).to({scaleX:.25,scaleY:.25,alpha:.8},1E3,createjs.Ease.getPowInOut(2)):console.log("Cannot minify overlay: There is no active overlay.")};
StageManager.removeOverlay=function(){this._overlay?(Common.removeTweens(this._overlay.container),createjs.Tween.get(this._overlay.container,{loop:!1,override:!0}).to({scaleX:0,scaleY:0,alpha:.5},500,createjs.Ease.getPowInOut(2)).call(function(){this._stage.removeChild(this._overlay.container);this._overlay=null}.bind(this))):console.log("Cannot remove overlay: There is no active overlay.")};StageManager.handleActivityEnd=function(){StageManager.idle();null!=this._overlay&&StageManager.expandOverlay()};
StageManager.transition=function(a){this._currentScreen=a;a=a.container;this._overlay&&StageManager.minifyOverlay();if(null==this._stage)this._stage=this.createStage(),this._tranScreens.addChild(a);else{createjs.Ticker.setFPS(60);a.x-=a.width;this._tranScreens.getChildAt(0).x=0;this._tranScreens.addChildAt(a,0);Common.removeTweens(this._tranScreens.getChildAt(1),!0);for(a=1;a<this._tranScreens.numChildren-1;a++)this._tranScreens.removeChildAt(a);createjs.Tween.get(this._tranScreens,{loop:!1,override:!0}).to({x:this._stage.canvas.width},
1E3,createjs.Ease.getPowInOut(2)).call(function(){this._tranScreens.removeChildAt(1);this._tranScreens.x=this._tranScreens.getChildAt(0).x=0;createjs.Ticker.setFPS(30)}.bind(this))}};