var Common=function(){};Common.replaceLastClass=function(a,b){var c=a.classList;c.remove(c[c.length-1]);c.add(b)};Common.toClassID=function(a){return"c"+a};Common.getRandomNumber=function(a,b){return Math.floor(Math.random()*(b-a+1)+a)};Common.removeTweens=function(a,b){if(a){if(a.numChildren)for(var c=0;c<a.numChildren;c++)Common.removeTweens(a.getChildAt(c),b);if(!a.persistant||b)createjs.Ticker.removeEventListener("tick",a),createjs.Tween.removeTweens(a)}};
Common.removeHTMLElements=function(a){if(a){if(a.numChildren)for(var b=0;b<a.numChildren;b++)Common.removeHTMLElements(a.getChildAt(b));$("#placeholder ."+Common.toClassID(a.id)).remove()}};window.addEventListener("resize",resize);function initCanvas(){StageManager.init("canvas");StageManager.idle()}function resize(){StageManager.resize()}
function showDebugInformation(){setTimeout(function(){var a=createjs.Ticker.getMeasuredFPS(),a=Math.round(100*a)/100;console.log("FPS: "+a+" | Active tweens: "+createjs.Tween._tweens.length+" | Ticker job count: "+createjs.Ticker._listeners.tick.length);showDebugInformation()},1E3)}var MessageInterpreter=function(){};
MessageInterpreter.interpret=function(a){switch(a.cmd){case "show":StageManager.draw(this.getScreen(a),a.overlay);break;case "update":StageManager.update(a);break;case "expand":StageManager.expandOverlay();break;case "minify":StageManager.minifyOverlay();break;case "remove":StageManager.removeOverlay();break;default:console.log("Error: Unknown command "+a.cmd)}};
MessageInterpreter.getScreen=function(a){try{return eval("(new "+a.screen+"(data))")}catch(b){try{return new window[a.screen](a)}catch(c){return console.log("ReferenceError: Screen "+a.screen+" is not defined."),null}}};var BuildPairs=function(a){this._data=a;this._selected={};this._drawable=[];this._submitted=this._initialized=!1};
BuildPairs.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background3.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new WordPairs(this._data.answers,
this.selected.bind(this)));this._drawable.push(new SubmitButton(this.submit.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._drawable.push(new WordPairs(this._data.answers,null))}this._initialized=!0};
BuildPairs.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
BuildPairs.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "SubmitButton":a.x=b.width;a.y=b.height;break;case "WordPairs":a.x=b.width/2,a.y=.7*b.height}};
BuildPairs.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};BuildPairs.prototype.selected=function(a){this._selected=a};
BuildPairs.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd(this))}};var BuildPairsSolution=function(a){this._data=a;this._drawable=[];this._initialized=!1};
BuildPairsSolution.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background3.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._drawable.push(new WordPairs(this._data.answers,null,this._data.solution));"student"===this._data.view&&this._drawable.push(new HeaderDisplay("Score: +"+this._data.score));this._initialized=!0};
BuildPairsSolution.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
BuildPairsSolution.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "WordPairs":a.x=b.width/2,a.y=.7*b.height}};var CatchEmAll=function(a){this._data=a;this._hitList=[];this._missList=[];this._drawable=[];this._submitted=this._initialized=!1};
CatchEmAll.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/apple-tree.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),
this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer)}this._movingPlatform=new MovingPlatform;this._drawable.push(this._movingPlatform);this._drawable.push(new CatchField(this._data.answers,this._data.difficulty,this.hitTest.bind(this)));this._initialized=!0};CatchEmAll.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
CatchEmAll.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "CatchField":a.x=0;a.y=0;break;case "MovingPlatform":a.x=0,a.y=0}};
CatchEmAll.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};
CatchEmAll.prototype.hitTest=function(a){var b=a.x,c=a.width/2;a=a.text;if(this._movingPlatform.hitTestBetween(b-c,b+c))return 0>this._hitList.indexOf(a)&&this._hitList.push(a),!0;0>this._missList.indexOf(a)&&this._missList.push(a);return!1};
CatchEmAll.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"hits" : '+JSON.stringify(this._hitList)+',"misses" : '+JSON.stringify(this._missList)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd(this))}};var CatchEmAllSolution=function(a){this._data=a;this._drawable=[];this._initialized=!1};
CatchEmAllSolution.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/apple-tree.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._drawable.push(new CorrectWrongDisplay(this._data.answers));"student"===this._data.view&&this._drawable.push(new HeaderDisplay("Score: +"+this._data.score));this._initialized=!0};
CatchEmAllSolution.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
CatchEmAllSolution.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "CorrectWrongDisplay":a.x=0,a.y=0}};var BackgroundImage=function(a){this._imagePath=a};BackgroundImage.prototype.addTo=function(a){a.name="BackgroundImage";this.createBackgroundImage(a.width,a.height,this._imagePath,a)};
BackgroundImage.prototype.createBackgroundImage=function(a,b,c,d){var e=new createjs.Bitmap(c);e.image.onload=function(){e.scaleX=a/e.image.width;e.scaleY=b/e.image.height;d.addChild(e)}.bind(this)};var ButtonPanel=function(a,b,c,d){this._values=a;this._minified=b;this._setSelected=c;this._stats=d;this._buttons=[];this._initialized=!1};
ButtonPanel.prototype.addTo=function(a){a.name="ButtonPanel";var b=a.width>=a.height,c=a.width;this._minified&&b&&(c/=2);var d=a.height/2;this._minified&&!b&&(d*=.7);var e=a.width/60,f=a.height/50,g=this._values.length,b=this._minified||!b?1:2,h=Math.ceil(g/b),l=(c-e*(b+3))/b,h=(d-f*(h+3))/h,c=this.createMasterPanel(c-2*e,d-2*f);a.addChild(c);if(0<this._buttons.length){for(var m=[],d=0;d<this._buttons.length;d++)m.push(null!=this._buttons[d].clicked);this._buttons=[]}for(d=0;d<g;d++){var k=this._values[d],
p=d%b,q=Math.floor(d/b),n=void 0;void 0!=this._stats&&(n=this._stats[d].correct);var r=void 0==m?!1:m[d],n=this.createButtonPanel(l,h,void 0!=this._stats?this._stats[d].selected:!1,n);n.x=e+p*(e+l)+c.x;n.y=f+q*(f+h)+c.y;n.label=k.toString();this._buttons.push(n);r&&n.dispatchEvent("click");k=this.createButtonLabel(l-e,h,k);k.x=n.x+l/2;p=k.getMeasuredHeight()/k.lineHeight;k.y=n.y+h/2-(p-1)*k.lineHeight/2;a.addChild(n,k);void 0!=this._stats&&this.createStats(a,n,this._stats[d].amount,this._stats[d].selected)}this._initialized=
!0};ButtonPanel.prototype.createMasterPanel=function(a,b){var c=new createjs.Shape;c.graphics.beginFill("#d3d3d3").drawRect(0,0,a,b);c.x=-a/2;c.y=-b/2;c.alpha=.4;return c};
ButtonPanel.prototype.createButtonPanel=function(a,b,c,d){function e(a){null==a.target.clicked?(a.target.filters=[new createjs.ColorFilter(0,0,0,1,255,203,151,0)],a.target.clicked=1):(a.target.filters=a.isTouch?[new createjs.ColorFilter(1,1,1,1,0,0,0,0)]:[new createjs.ColorFilter(1,1,1,1,-25,-25,-25,0)],a.target.clicked=null);a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h);a=[];for(var b=0;b<this._buttons.length;b++)null!=this._buttons[b].clicked&&a.push(this._buttons[b].label);
this._setSelected(a)}function f(a){if(null==a.target.clicked){switch(a.type){case "mouseover":a.target.filters=[new createjs.ColorFilter(1,1,1,1,-25,-25,-25,0)];break;case "mouseout":a.target.filters=[new createjs.ColorFilter(1,1,1,1,0,0,0,0)]}a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h)}}var g=new createjs.Shape;void 0==d?g.graphics.beginFill("#d3d3d3"):d?c?g.graphics.beginFill("#5cb85c"):(g.graphics.beginFill("#d3d3d3"),g.filters=[new createjs.ColorFilter(1,1,1,1)],
g.cache(0,0,a,b),g.handleEvent=function(){this.updateCache()},createjs.Ticker.addEventListener("tick",g),createjs.Tween.get(g,{loop:!0}).wait(200).call(function(a){createjs.Tween.get(a,{loop:!1}).to({redMultiplier:.36,greenMultiplier:.72,blueMultiplier:.36},400,createjs.Ease.getPowInOut(2)).to({redMultiplier:1,greenMultiplier:1,blueMultiplier:1},400,createjs.Ease.getPowInOut(2))},[g.filters[0]]).wait(800)):c?g.graphics.beginFill("#f5756e"):g.graphics.beginFill("#d3d3d3");g.graphics.drawRect(0,0,a,
b);g.width=a;g.height=b;g.shadow=new createjs.Shadow("#333333",5,5,10);null!=this._setSelected&&(g.on("click",e.bind(this)),g.on("mouseover",f.bind(this)),g.on("mouseout",f.bind(this)));return g};ButtonPanel.prototype.createButtonLabel=function(a,b,c){var d=40,e=new createjs.Text;e.text=c.toString();e.font=d+"px Dimbo";e.lineWidth=a;e.lineHeight=1.5*d;e.color="black";e.textAlign="center";for(e.textBaseline="middle";e.getMeasuredHeight()>b;)d-=2,e.lineHeight=1.5*d,e.font=d+"px Dimbo";return e};
ButtonPanel.prototype.createStats=function(a,b,c,d){for(var e=0,f=0;f<this._stats.length;f++)e+=this._stats[f].amount;f=this.createStatBar(b.height);f.x=b.x;f.y=b.y;this.animateStatBar(f,b.width,c,e,this._initialized);var g=this.createStatLabel(a.width,a.height,c);g.x=b.x+b.width*c/e;g.y=b.y;this.animateStatLabel(g,this._initialized);a.addChild(f,g);d&&(c=this.createSelectedHighlight(b.width,b.height),c.x=b.x,c.y=b.y,a.addChild(c))};
ButtonPanel.prototype.createStatBar=function(a){var b=new createjs.Shape;b.graphics.beginFill("#000").drawRect(0,0,0,a);b.alpha=.5;return b};ButtonPanel.prototype.animateStatBar=function(a,b,c,d,e){createjs.Tween.get(a.graphics.command,{loop:!1}).wait(e?0:1E3).to({w:b*c/d},e?0:2E3,createjs.Ease.getPowInOut(2))};
ButtonPanel.prototype.createStatLabel=function(a,b,c){a=Math.floor(Math.max(a/40,b/30));c=new createjs.Text(c.toString());c.font=a+"px Dimbo";c.color="#000";c.textAlign="left";c.textBaseline="top";c.alpha=0;return c};ButtonPanel.prototype.animateStatLabel=function(a,b){createjs.Tween.get(a,{loop:!1}).wait(b?0:2700).to({alpha:.8},b?0:1E3,createjs.Ease.getPowInOut(2))};
ButtonPanel.prototype.createSelectedHighlight=function(a,b){var c=new createjs.Shape;c.graphics.setStrokeStyle(6).beginStroke("black").drawRect(0,0,a,b);c.alpha=.9;return c};var CatchField=function(a,b,c){this._wordPool=a;this._velocity=1E4/b;this._hitTest=c;this._running=!1;this._interval=6E3/b;this._dummy=new createjs.Shape;this._dummy.persistant=!0;this._apples=[]};
CatchField.prototype.addTo=function(a){a.name="CatchField";this._container=a;if(this._running)for(var b=this._apples,c=0;c<b.length;c++){var d=b[c];d.x*=a.width/this._width;a.addChild(d)}else this._running=!0,this.tick(this._dummy);this._width=a.width;a.addChild(this._dummy)};
CatchField.prototype.tick=function(a){createjs.Tween.get(a,{loop:!0}).wait(this._interval).call(function(){var a=this._container,c=this.createApple(this.getRandomWord(),a.width,Math.max(a.width,a.height));this.animateApple(a,c,.85*a.height-this._appleSize/2,this._velocity);this._apples.push(c);a.addChild(c)}.bind(this))};
CatchField.prototype.createApple=function(a,b,c){this._appleSize=c/6;var d=new createjs.Container;d.addChild(this.createAppleSprite(this._appleSize));d.addChild(this.createAppleLabel(c/12,a));d.x=Common.getRandomNumber(this._appleSize/2,b-this._appleSize/2);d.y=-this._appleSize;d.width=this._appleSize;d.text=a.toString();return d};CatchField.prototype.getRandomWord=function(){return this._wordPool[Common.getRandomNumber(0,this._wordPool.length-1)]};
CatchField.prototype.animateApple=function(a,b,c,d){b.persistant=!0;createjs.Tween.get(b,{loop:!1}).to({y:c},d).call(function(c){this._hitTest(b)?createjs.Tween.get(b,{loop:!1}).to({rotation:360,alpha:0,scaleX:0,scaleY:0,y:b.y+this._appleSize/2},500).call(function(c){this._apples.splice(this._apples.indexOf(b),1);a.removeChild(b)}.bind(this)):createjs.Tween.get(b,{loop:!1}).to({y:b.y+a.height},d).call(function(c){this._apples.splice(this._apples.indexOf(b),1);a.removeChild(b)}.bind(this))}.bind(this))};
CatchField.prototype.createAppleSprite=function(a){var b=new createjs.Bitmap("img/apple.png");b.image.onload=function(){b.scaleX=b.scaleY=a/b.image.width};b.x-=this._appleSize/2;b.y-=this._appleSize/2;return b};CatchField.prototype.createAppleLabel=function(a,b){var c=.5*a,d=new createjs.Text;d.text=b.toString();d.font=c+"px Dimbo";d.color="#d3d3d3";d.lineWidth=this._appleSize;d.textAlign="center";d.textBaseline="middle";return d};var CorrectWrongDisplay=function(a){this._answers=a};
CorrectWrongDisplay.prototype.addTo=function(a){a.name="CorrectWrongDisplay";var b=this.createWordList(this._answers.correct,!0,a.width,a.height);b.y=.5*a.height;var c=this.createWordList(this._answers.wrong,!1,a.width,a.height);c.y=.7*a.height;var d=this.createBackgroundPanel(.95*a.width,.4*a.height);d.x+=.5*a.width;d.y+=.65*a.height;a.addChild(d,b,c)};
CorrectWrongDisplay.prototype.createWordList=function(a,b,c,d){d=Math.floor(Math.max(c/30,d/25));var e=new createjs.Text;e.font=d+"px Dimbo";e.lineWidth=.9*c;e.lineHeight=1.1*d;e.textAlign="left";e.textBaseline="middle";e.x=.05*c;b?(e.text="Correct: "+this.concatenateWords(a),e.color="green"):(e.text="Wrong: "+this.concatenateWords(a),e.color="#f0261b");return e};
CorrectWrongDisplay.prototype.createBackgroundPanel=function(a,b){var c=new createjs.Container,d=new createjs.Shape;d.graphics.beginFill("#d3d3d3").drawRect(0,0,a,b);d.x=-a/2;d.y=-b/2;var e=this.createDivisorLine(a);c.addChild(d,e);return c};CorrectWrongDisplay.prototype.createDivisorLine=function(a){var b=new createjs.Shape;b.graphics.setStrokeStyle(3).beginStroke("black").moveTo(-a/2,0).lineTo(a/2,0).endStroke();b.alpha=.5;return b};
CorrectWrongDisplay.prototype.concatenateWords=function(a){for(var b="",c=0;c<a.length;c++)0<c&&(b+=", "),b+=a[c];return b};var DifficultyMeter=function(a){this._numStars=5;this._value=Math.min(a,this._numStars)};DifficultyMeter.prototype.addTo=function(a){a.name="DifficultyMeter";if(!(0>this._value))for(var b=0;b<this._numStars;b++){var c=this.createStar(a.width,a.height,b);a.addChild(c)}};
DifficultyMeter.prototype.createStar=function(a,b,c){var d=Math.max(a/80,b/60);a=Math.max(a/30,b/25);b=new createjs.Shape;c<this._value?b.graphics.beginFill("#F0261B"):b.graphics.beginFill("#333333");b.graphics.drawPolyStar(0,0,d,5,.6,-90);b.x=-((this._numStars/2-c)*a)+a/2;b.y=0;return b};var DisplayImage=function(a){this._imagePath=a};DisplayImage.prototype.addTo=function(a){a.name="DisplayImage";this.createImageObject(a.width,a.height,this._imagePath,a)};
DisplayImage.prototype.createImageObject=function(a,b,c,d){var e=new createjs.Bitmap(c),f=a>=b;e.image.onload=function(){var c=Math.min(.4*a/e.image.width,.5*b/e.image.height);f||(c*=.9);e.scaleX=e.scaleY=c;e.x=-(e.image.width*e.scaleX)/2;e.y=-(e.image.height*e.scaleY)/2;d.addChild(e)};e.shadow=new createjs.Shadow("#333333",5,5,10)};
var FireworkEffect=function(){this._sprite=new createjs.Sprite(new createjs.SpriteSheet({images:["img/spritesheet_sparkle.png"],frames:{width:200,height:200,regX:100,regY:100}}));this._sparkles=[]};FireworkEffect.prototype.addTo=function(a){this._container=a;for(a=0;a<this._sparkles.length;a++)this.tick(this._sparkles[a])};
FireworkEffect.prototype.tick=function(a){0>this._container.getChildIndex(a)&&this._container.addChild(a);for(var b=a.numChildren,c=b-1;0<=c;c--){var d=a.getChildAt(c);d.vY+=.8;d.vX*=.99;d.x+=1*d.vX;d.y+=1*d.vY;d.scaleX=d.scaleY=d.scaleX+1*d.vS;d.alpha+=1*d.vA;(0>=d.alpha||d.y>this._container.height)&&a.removeChild(d)}0==b?(this._container.removeChild(a),this._sparkles.splice(this._sparkles.indexOf(a),1)):createjs.Tween.get(this._container).wait(createjs.Ticker.interval).call(this.tick.bind(this),
[a])};
FireworkEffect.prototype.explosionAnimation=function(a,b,c,d){for(var e=new createjs.Container,f=this._container.width,g=this._container.height,h=0;h<a;h++){var l=this._sprite.clone();l.x=b;l.y=c;l.rotation=360*Math.random();l.alpha=.5*Math.random()+.5;var m=Math.min(f/1E3,g/1E3);l.scaleX=l.scaleY=Math.random()*m+m;var m=2*Math.PI*Math.random(),k=30*(Math.random()-.5)*d;l.vX=Math.cos(m)*k;l.vY=Math.sin(m)*k;l.vS=.2*(Math.random()-.5);l.vA=.02*-Math.random()-.01;l.gotoAndPlay(Math.random()*l.spriteSheet.getNumFrames());e.addChild(l)}this._sparkles.push(e);
this._running||this.tick(e)};var FooterTextDisplay=function(a){this._value=a};FooterTextDisplay.prototype.addTo=function(a){a.name="FooterTextDisplay";this._label=this.createLabel(a.width,a.height);a.addChild(this._label)};FooterTextDisplay.prototype.createLabel=function(a,b){var c=Math.floor(Math.max(a/40,b/30)),d=new createjs.Text;d.text=this._value.toString();d.font=c+"px Dimbo";d.color="#f0261b";d.textAlign="center";d.textBaseline="bottom";return d};
FooterTextDisplay.prototype.update=function(a){this._value=a;this._label.text=a.toString()};var HeaderDisplay=function(a){this._value=a};HeaderDisplay.prototype.addTo=function(a){a.name="HeaderDisplay";var b=this.createLabel(a.width,a.height,this._value),c=this.createBackgroundPanel(b.getMeasuredWidth(),b.getMeasuredHeight());a.addChild(c,b)};
HeaderDisplay.prototype.createLabel=function(a,b,c){a=Math.floor(Math.max(a/23,b/20));b=new createjs.Text;b.text=c.toString();b.font=a+"px Dimbo";b.color="#f0261b";b.textAlign="left";b.textBaseline="top";return b};HeaderDisplay.prototype.createBackgroundPanel=function(a,b){var c=new createjs.Shape;c.graphics.beginFill("#d3d3d3").drawRoundRectComplex(0,0,a+b/2,1.5*b,0,0,b,0);return c};
var HiddenImage=function(a,b,c,d){this._imagePath=a;b=Math.min(b,25);c=Math.min(c,25);this._rowCount=b;this._colCount=c;this._numTiles=b*c;this._wallMap=Array(c);for(a=0;a<c;a++){this._wallMap[a]=Array(b);for(var e=0;e<b;e++)this._wallMap[a][e]=new createjs.Shape}this._clearTrigger=d};HiddenImage.prototype.addTo=function(a){a.name="HiddenImage";this.createImage(a)};
HiddenImage.prototype.createImage=function(a){var b=new createjs.Bitmap(this._imagePath),c=new createjs.Container;b.image.onload=function(){b.scaleX=b.scaleY=Math.min(.9*a.width/b.image.width,.6*a.height/b.image.height);var d=b.image.width*b.scaleX,e=b.image.height*b.scaleY;c.x=-d/2;c.y=-e/2;c.addChild(b,this.createWall(d,e));a.addChild(c)}.bind(this)};
HiddenImage.prototype.createWall=function(a,b){for(var c=new createjs.Container,d=a/this._colCount,e=b/this._rowCount,f=0;f<this._colCount;f++)for(var g=0;g<this._rowCount;g++){var h=this._wallMap[f][g];h&&(h.graphics.clear().setStrokeStyle(2).beginStroke("#fff").beginFill(f%2==g%2?"#a11201":"#c2382e").drawRect(f*d,g*e,d,e),h.x=d*(f+.5),h.y=e*(g+.5),h.regX=d*(f+.5),h.regY=e*(g+.5),h.cache(f*d,g*e,d,e),c.addChild(h))}return c};
HiddenImage.prototype.removeRandomTile=function(a){for(;this._numTiles&&0<a--;){var b=Common.getRandomNumber(0,this._numTiles),c=0;a:for(;c<this._colCount;c++)for(var d=0;d<this._rowCount;d++){var e=this._wallMap[c][d];if(e&&(b--,0>=b)){this._wallMap[c][d]=null;this.removeTile(e);break a}}}};
HiddenImage.prototype.removeTile=function(a){0>=this._numTiles||(this._numTiles--,0==this._numTiles&&this._clearTrigger(),a.filters=[new createjs.ColorFilter(1.5,1.5,1,1)],a.updateCache(),createjs.Tween.get(a,{loop:!1}).wait(500).to({alpha:0,rotation:540},2E3,createjs.Ease.getPowInOut(3)).call(function(a){a.parent.removeChild(a)},[a]))};HiddenImage.prototype.uncoverAll=function(){this.removeRandomTile(this._numTiles)};var HighscoreList=function(a){this._ranklist=a};
HighscoreList.prototype.addTo=function(a){this._container=a;a.name="HighscoreList";for(var b=.9*a.width,c=a.height/9,d=0;d<this._ranklist.length;d++){var e=-b/2,f=c*d,g=this._ranklist[d],h=Math.min(.8*a.width,.8*a.height)/(9*window.devicePixelRatio),l=h-h/5*Math.min(d,2.5),h=l/80*c,m=this.createBackgroundPanel(b,c,d);m.x=e;m.y=f;var k=this.createRankLabel(l,d);k.x=e+.15*b;k.y=f+c/2;var p=this.createNameLabel(l,g.name);p.x=e+.2*b;p.y=f+c/2;var q=this.createScoreLabel(l,g.score);q.x=e+.7*b;q.y=f+c/
2;var n=this.createChangeIcon(h,g.change);n.x=e+.85*b;n.y=f+c/2;g=this.createChangeLabel(l,g.change);g.x=e+.93*b;g.y=f+c/2;a.addChild(m,k,p,q,g);0==d&&(g=this.createCrownIcon(h),g.x+=e+.06*b,g.y+=f+c/2)}};
HighscoreList.prototype.createBackgroundPanel=function(a,b,c){var d=new createjs.Shape;d.graphics.beginFill("#d3d3d3").drawRect(0,0,a,b);d.shadow=new createjs.Shadow("#333333",5,5,10);switch(c){case 0:d.filters=[new createjs.ColorFilter(1,1,1,1,75,75,10,0)];break;case 1:d.filters=[new createjs.ColorFilter(1,1,1,1,30,30,10,0)];break;case 2:d.filters=[new createjs.ColorFilter(1,1,1,1,15,15,10,0)];break;case 3:d.filters=[new createjs.ColorFilter(1,1,1,1,7,7,4,0)]}d.cache(0,0,a,b);return d};
HighscoreList.prototype.createCrownIcon=function(a){var b=new createjs.Bitmap("img/crown.jpg");b.image.onload=function(){var c=a/b.image.height;b.scaleX=b.scaleY=c;b.x-=b.image.width*c/2;b.y-=b.image.height*c/2;this._container.addChild(b)}.bind(this);return b};HighscoreList.prototype.createRankLabel=function(a,b){var c=new createjs.Text;c.text=b+1+" .";c.font=a+"px Dimbo";c.color="#f0261b";c.textAlign="center";c.textBaseline="middle";return c};
HighscoreList.prototype.createNameLabel=function(a,b){var c=new createjs.Text;c.text=b.toString();c.font=a+"px Dimbo";c.color="#f0261b";c.textAlign="left";c.textBaseline="middle";return c};HighscoreList.prototype.createScoreLabel=function(a,b){var c=new createjs.Text;c.text=b.toString();c.font=a+"px Dimbo";c.color="#f0261b";c.textAlign="center";c.textBaseline="middle";return c};
HighscoreList.prototype.createChangeIcon=function(a,b){var c;c=0<b?new createjs.Bitmap("img/rankUp.png"):0>b?new createjs.Bitmap("img/rankDown.png"):new createjs.Bitmap("img/rankSame.png");c.image.onload=function(){var b=a/c.image.height;c.scaleX=c.scaleY=b;c.x-=c.image.width*b/2;c.y-=c.image.height*b/2;this._container.addChild(c)}.bind(this);return c};
HighscoreList.prototype.createChangeLabel=function(a,b){var c=new createjs.Text;0<b&&(b="+"+b.toString());0==b&&(b="-");c.text=b;c.font=a+"px Dimbo";c.color=0<b?"#3bb742":0>b?"#f0261b":"#496da3";c.textAlign="center";c.textBaseline="middle";return c};HighscoreList.prototype.update=function(a){this._ranklist=a;this._container.removeAllChildren();this.addTo(this._container)};var InteractiveImage=function(a,b,c){this._imagePath=a;this._submit=b;this._stats=c;this._initialized=!1};
InteractiveImage.prototype.addTo=function(a){this._container=a;a.name="InteractiveImage";this.createInteractiveImage(a);this.preloadPinIcon()};
InteractiveImage.prototype.createInteractiveImage=function(a){var b=new createjs.Bitmap(this._imagePath),c=a.width/20;b.image.onload=function(){b.scaleX=b.scaleY=Math.min(.9*a.width/b.image.width,(a.height/2+c)/b.image.height);b.x=-(b.image.width*b.scaleX)/2;b.y=-(b.image.height*b.scaleY)/2;this._container.addChild(b);void 0!=this._stats&&(this.createStats(this._stats,b),this._initialized=!0)}.bind(this);b.shadow=new createjs.Shadow("#333333",5,5,10);b.on("click",function(c){if(null!=this._submit||
c.isAnswer){var e=this.createPin(a.width,a.height);e.x=c.localX*b.scaleX+b.x;e.y=c.localY*b.scaleY+b.y;c.selected&&(e.filters=[new createjs.ColorFilter(0,0,0,1,255,99,71,0)]);if(c.isAnswer){e.alpha=0;var f=e.x,g=e.y;e.x+=50;e.y-=50;e.alpha=0;var h=Math.round(300*Math.random());this._initialized||(h+=1E3);createjs.Tween.get(e,{loop:!1}).wait(h).to({x:f,y:g,alpha:1},300,createjs.Ease.getPowInOut(2))}null!=this._submit&&this._submit([Math.round(c.localX),Math.round(c.localY)])}}.bind(this))};
InteractiveImage.prototype.createPin=function(a,b){var c=new createjs.Bitmap("img/pin.png");c.image.onload=function(){var d=Math.min(.05*a/c.image.width,.05*b/c.image.height);c.scaleX=c.scaleY=d;c.y-=c.image.height*d;c.cache(0,0,c.image.width,c.image.height);this._container.addChild(c)}.bind(this);return c};InteractiveImage.prototype.preloadPinIcon=function(){(new createjs.LoadQueue).loadFile("img/pin.png")};
InteractiveImage.prototype.createStats=function(a,b){var c=a.correct;this.createCorrectArea(c.type,c.data,b);for(var c=a.answers,d=0;d<c.length;d++){var e=new createjs.Event("click");e.localX=c[d].x;e.localY=c[d].y;e.selected=c[d].selected;e.isAnswer=!0;b.dispatchEvent(e)}};
InteractiveImage.prototype.createCorrectArea=function(a,b,c){var d=new createjs.Shape;switch(a){case "polygon":d.graphics.beginFill("green");d.graphics.moveTo(this.convertLocalToAbsoluteX(b[0].x,c),this.convertLocalToAbsoluteY(b[0].y,c));for(a=1;a<b.length;a++)d.graphics.lineTo(this.convertLocalToAbsoluteX(b[a].x,c),this.convertLocalToAbsoluteY(b[a].y,c));d.graphics.lineTo(this.convertLocalToAbsoluteX(b[b.length-1].x,c),this.convertLocalToAbsoluteY(b[b.length-1].y,c));d.graphics.endFill();break;case "circle":a=
Math.round(Math.sqrt(Math.pow(b.center.x-b.radius.x,2)+Math.pow(b.center.y-b.radius.y,2))*c.scaleX),d.graphics.beginFill("green").drawCircle(this.convertLocalToAbsoluteX(b.center.x,c),this.convertLocalToAbsoluteY(b.center.y,c),a)}d.alpha=.7;this._container.addChild(d)};InteractiveImage.prototype.convertLocalToAbsoluteX=function(a,b){return a*b.scaleX+b.x};InteractiveImage.prototype.convertLocalToAbsoluteY=function(a,b){return a*b.scaleY+b.y};
var LabelIterator=function(a,b,c){this._values=a;this._interval=Math.max(b,0);this.onChange=c;this._currentIndex=0;this._running=!1};LabelIterator.prototype.addTo=function(a){a.name="LabelIterator";this._label=this.createLabel(a.width,a.height);this._running?(this.updateLabel(),this.updateColor()):(this._running=!0,this.tick());a.addChild(this._label)};
LabelIterator.prototype.createLabel=function(a,b){var c=Math.floor(Math.max(a/20,b/20)),d=new createjs.Text;d.font=c+"px Dimbo";d.color="#000";d.textAlign="center";d.textBaseline="middle";return d};LabelIterator.prototype.updateLabel=function(){this._label.text=this._values[this._currentIndex]};
LabelIterator.prototype.tick=function(){this.updateLabel();this.updateColor();this._label.persistant=!0;createjs.Tween.get(this._label,{loop:!1}).wait(this._interval).call(function(){this._currentIndex=(this._currentIndex+1)%this._values.length;this.tick()}.bind(this))};LabelIterator.prototype.updateColor=function(){null!=this.onChange&&(this.onChange(this._values[this._currentIndex])?this._label.color="#f0261b":this._label.color="#000")};var MovingPlatform=function(){this._lastKeyPressed=null};
MovingPlatform.prototype.addTo=function(a){a.name="MovingPlatform";this._width=a.width;this._height=a.height;var b=this.createPlatform(Math.max(a.width,a.height)/6,a.height/20,"img/basket.png",a);b.x+=.5*a.width+b.width/2;b.y+=.85*a.height;this._platform=b;this.createPlatformControls(b,a)};
MovingPlatform.prototype.createPlatform=function(a,b,c,d){var e=new createjs.Bitmap(c);e.image.onload=function(){e.scaleX=e.scaleY=a/e.image.width;e.x-=e.image.width*e.scaleX/2;e.regX=e.image.width/2;d.addChild(e)};e.width=a;e.height=b;return e};
MovingPlatform.prototype.createPlatformControls=function(a,b){window.onkeydown=function(b){this._lastKeyPressed=b=b.key;"a"===b||"A"===b||"ArrowLeft"===b||"Left"===b?this.movePlatform(a,0):"d"!==b&&"D"!==b&&"ArrowRight"!==b&&"Right"!==b||this.movePlatform(a,this._width)}.bind(this);window.onkeyup=function(b){this._lastKeyPressed===b.key&&this.stopPlatform(a)}.bind(this);this.createHitArea(b);b.on("mousedown",function(b){this._lastKeyPressed="MouseClick";this.movePlatform(a,b.rawX)}.bind(this));b.on("pressmove",
function(b){this._lastKeyPressed="MouseClick";this.movePlatform(a,b.rawX)}.bind(this));b.on("pressup",function(b){"MouseClick"===this._lastKeyPressed&&this.stopPlatform(a)}.bind(this))};MovingPlatform.prototype.createHitArea=function(a){var b=new createjs.Shape;b.graphics.beginFill("#000").drawRect(0,0,a.width,a.height);a.hitArea=b};
MovingPlatform.prototype.movePlatform=function(a,b){b=Math.max(Math.min(b,this._width-a.width/2),a.width/2);a.x>b?(0<a.scaleX&&(a.scaleX*=-1),createjs.Tween.get(a,{loop:!1,override:!0}).to({x:b},1500*(a.x-b)/this._width,createjs.Ease.getPowInOut(1))):a.x<b&&(0>a.scaleX&&(a.scaleX*=-1),createjs.Tween.get(a,{loop:!1,override:!0}).to({x:b},1500*(b-a.x)/this._width,createjs.Ease.getPowInOut(1)))};MovingPlatform.prototype.stopPlatform=function(a){createjs.Tween.removeTweens(a)};
MovingPlatform.prototype.hitTestBetween=function(a,b){return this.hitTest(a)||this.hitTest(b)||a<this._platform.x&&b>this._platform.x+this._platform.width?!0:!1};MovingPlatform.prototype.hitTest=function(a){return Math.abs(this._platform.x-a)<=this._platform.width/2?!0:!1};
var RaceProgressionDisplay=function(a,b){this._spriteWidth=400;this._spriteHeight=248;this._sprite=new createjs.Sprite(new createjs.SpriteSheet({images:["img/spritesheet_horse.png"],frames:{width:this._spriteWidth,height:this._spriteHeight,regX:Math.round(this._spriteWidth/2),regY:Math.round(this._spriteHeight/2)}}));this._sprite.gotoAndStop(7);this._groups=a;this._numSteps=b};
RaceProgressionDisplay.prototype.addTo=function(a){this._container=a;a.name="RaceProgressionDisplay";var b=this._groups.length,c=.7*a.width,d=a.height/(2*b),e=a.width/10;this._stepWidth=c/this._numSteps;this._horseSprites=[];this._rankCounter=1;for(var f=0;f<b;f++){var g=this.createLabel(this._groups[f].name,c);g.x=-c/2+.9*e;g.y=d*(f+.5);var h=this.createProgressBar(this._groups[f].position,this._numSteps,this._groups[f].color,c,d);h.x=-c/2+e;h.y=d*f;a.addChild(h,g)}for(f=1;f<this._numSteps;f++)a.addChild(this.createStepDivisor(-c/
2+e+f*this._stepWidth,d*b));for(f=0;f<b;f++)g=this.createHorseSprite(),g.x=-c/2+this._groups[f].position*this._stepWidth+this._stepWidth/2+e,g.y=d*(f+.5),g.scaleX=g.scaleY=3*d/5/this._spriteHeight,g.position=this._groups[f].position,a.addChild(g),this._horseSprites[this._groups[f].name]=g,g.position>=this._numSteps-1&&this.createRankLabel(f)};
RaceProgressionDisplay.prototype.createStepDivisor=function(a,b){var c=new createjs.Shape;c.graphics.setStrokeStyle(3).beginStroke("black").moveTo(a,0).lineTo(a,b).endStroke();c.alpha=.5;return c};RaceProgressionDisplay.prototype.createLabel=function(a,b){var c=b/20,d=new createjs.Text;d.text=a.toString();d.font=c+"px Dimbo";d.color="#000";d.textAlign="right";d.textBaseline="middle";return d};
RaceProgressionDisplay.prototype.createProgressBar=function(a,b,c,d,e){a=new createjs.Shape;a.graphics.beginFill(c).drawRect(0,0,d,e);a.shadow=new createjs.Shadow("#333333",5,5,10);return a};RaceProgressionDisplay.prototype.createHorseSprite=function(){return this._sprite.clone()};
RaceProgressionDisplay.prototype.update=function(a,b){var c=this._horseSprites[a];if(!c)return console.log("Group "+a+" not found."),!1;if(0<=c.position+b&&c.position<this._numSteps-1){var d=c.position;c.position=Math.max(Math.min(c.position+b,this._numSteps-1),0);d=c.position-d;createjs.Tween.get(c,{loop:!1}).to({scaleX:0>d?-c.scaleX/2:c.scaleX},0>d?200:0).to({scaleX:0>d?-c.scaleX:c.scaleX},0>d?200:0).call(c.play).to({x:c.x+d*this._stepWidth},1E3*Math.abs(d)).call(c.gotoAndStop,[7]).to({scaleX:c.scaleX},
0>d?200:0);for(c=this._groups.length-1;0<=c;c--)if(this._groups[c].name===a){this._groups[c].position+=d;this._groups[c].position==this._numSteps-1&&this.createRankLabel(c);break}return!0}return!1};
RaceProgressionDisplay.prototype.createRankLabel=function(a){var b;this._groups[a].rank?(b=this._groups[a].rank,this._rankCounter=Math.max(this._rankCounter,b)):(b=this._rankCounter,this._groups[a].rank=b);var c=this._container.width/30,d=new createjs.Text;d.text=b.toString()+". ";d.font=c+"px Dimbo";d.color="#f0261b";d.textAlign="right";d.textBaseline="middle";d.x=this._container.width/2;d.y=this._container.height/(2*this._groups.length)*(a+.5);this._rankCounter++;this._container.addChild(d)};
var RoundButton=function(a,b){this._value=a;this._action=b};RoundButton.prototype.addTo=function(a){a.name="RoundButton";var b=Math.min(a.width/4,a.height/5),c=this.createLabel(a.width,a.height,this._value),b=this.createBackgroundCircle(b);a.addChild(b,c)};RoundButton.prototype.createLabel=function(a,b,c){a=Math.floor(Math.min(a/10,b/10));b=new createjs.Text;b.text=c.toString();b.font="bold "+a+"px Dimbo";b.color="#d3d3d3";b.textBaseline="middle";b.textAlign="center";return b};
RoundButton.prototype.createBackgroundCircle=function(a){function b(b){switch(b.type){case "mouseover":b.target.filters=[new createjs.ColorFilter(1,1,1,1,-25,-25,-25,0)];break;case "mouseout":b.target.filters=[new createjs.ColorFilter(1,1,1,1,0,0,0,0)]}b.target.cache(-a,-a,2*a,2*a)}var c=new createjs.Shape;c.graphics.beginRadialGradientFill(["#F0261B","#C01E15"],[0,1],0,0,0,0,0,a).drawCircle(0,0,a);c.shadow=new createjs.Shadow("#000000",5,5,10);c.on("click",function(b){null!=this._action&&(b.target.filters=
[new createjs.ColorFilter(0,0,0,1,144,22,16,0)],b.target.cache(-a,-a,2*a,2*a),setTimeout(function(){b.target.filters=void 0;b.target.uncache()},150),this._action())}.bind(this));c.on("mouseover",b.bind(this));c.on("mouseout",b.bind(this));return c};var SubmitButton=function(a){this._submit=a};SubmitButton.prototype.addTo=function(a){a.name="SubmitButton";var b=this.createLabel(a.width,a.height),c=this.createBackgroundPanel(b.getMeasuredWidth(),b.getMeasuredHeight());a.addChild(c,b)};
SubmitButton.prototype.createLabel=function(a,b){var c=Math.floor(Math.max(a/23,b/20)),d=new createjs.Text;d.text="Submit";d.font=c+"px Dimbo";d.color="#f0261b";d.textAlign="right";d.textBaseline="bottom";return d};
SubmitButton.prototype.createBackgroundPanel=function(a,b){function c(a){switch(a.type){case "mouseover":a.target.filters=[new createjs.ColorFilter(1,1,1,1,-25,-25,-25,0)];break;case "mouseout":a.target.filters=[new createjs.ColorFilter(1,1,1,1,0,0,0,0)]}a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h)}var d=a+b/2,e=1.5*b,f=new createjs.Shape;f.graphics.beginFill("#d3d3d3").drawRoundRectComplex(0,0,d,e,b,0,0,0);f.x=-d;f.y=-e;f.on("click",function(a){null!=this._submit&&
(a.target.filters=[new createjs.ColorFilter(0,0,0,1,255,203,151,0)],a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h),this._submit())}.bind(this));f.on("mouseover",c.bind(this));f.on("mouseout",c.bind(this));return f};var TextBox=function(a){this._submit=a};
TextBox.prototype.addTo=function(a){a.name="TextBox";this._textBox?Common.replaceLastClass(this._textBox.htmlElement,Common.toClassID(a.id)):this._textBox=this.createTextBox(a.width,Common.toClassID(a.id));this._textBox.x=-this._textBox.htmlElement.offsetWidth/2;a.addChild(this._textBox)};
TextBox.prototype.createTextBox=function(a,b){var c=document.createElement("template");c.innerHTML='<div class="form-group '+b+'" id="textBox" style="width:60%; top:'+document.getElementById("header").offsetHeight+'px; left:0"><input class="form-control input-lg" type="text" placeholder="Enter suggestion" maxlength="200" style="font-family:\'Dimbo\'; font-size:2em;"></div>';c=c.content.firstChild;$("#placeholder").append(c);c.addEventListener("keydown",function(a){13==a.keyCode&&(a=c.getElementsByTagName("input")[0],
a.value&&(this._submit(a.value),a.value="",a=document.createElement("template"),a.innerHTML='<label id="submitInfoLabel" style="font-family:\'Dimbo\'; font-size:1.7em; padding-left:30px; position:absolute; top:-40px; left:0; color:#f0261b;">Submitted!</label>',a=a.content.firstChild,$("#textBox").append(a),$("#submitInfoLabel").hide(),$("#submitInfoLabel").show("drop",{},500,function(){setTimeout(function(){$("#submitInfoLabel").fadeOut();setTimeout(function(){$("#submitInfoLabel").remove()},400)},
1500)})))}.bind(this));return new createjs.DOMElement(c)};var TimeDisplay=function(a,b){this._currentTime=this._totalTime=Math.max(Math.round(a),0);this._tickTime=1E3;this._running=!1;this._submit=b;this._initialized=!1};
TimeDisplay.prototype.addTo=function(a){this._container=a;a.name="TimeDisplay";if(0<this._currentTime||!this._submit)this._radius=Math.max(a.width/9,a.height/7),this._backgroundCircle=this.createBackgroundCircle(),this._timeLabel=this.createTimeLabel(a.width,a.height,this._currentTime),this._progressArc=this.createProgressArc(a.width,a.height),this.updateProgressAnimation(),this._running&&this.startProgressAnimation(),a.addChild(this._backgroundCircle,this._progressArc,this._timeLabel),this._initialized||
(this.startTimer(!0),this._initialized=!0)};TimeDisplay.prototype.createBackgroundCircle=function(){var a=new createjs.Shape;a.graphics.beginFill("#d3d3d3").drawCircle(0,0,this._radius);a.filters=[new createjs.ColorFilter(1,1,1,1)];a.cache(-this._radius,0,this._radius,this._radius,2);return a};
TimeDisplay.prototype.createTimeLabel=function(a,b,c){a=Math.floor(Math.max(a/18,b/15));b=new createjs.Text;b.text=c.toString();b.font=a+"px Dimbo";b.color="#F0261B";b.x=.4*-this._radius;b.y=.4*this._radius;b.lineWidth=this._radius;b.textAlign="center";b.textBaseline="middle";return b};
TimeDisplay.prototype.createProgressArc=function(a,b){var c=Math.max(a/80,b/60),d=new createjs.Shape;d.graphics.setStrokeStyle(c).beginStroke("#F0261B").arc(0,0,this._radius,Math.PI/2,Math.PI);d.x=d.regX=0;d.y=d.regY=0;return d};TimeDisplay.prototype.startTimer=function(a){this._running||(this._running=!0,this.startProgressAnimation(),this.tick(new Date((new Date).getTime()-this._tickTime)),a||this.statusAnimation("resumed"))};
TimeDisplay.prototype.stopTimer=function(){this._running&&(this._running=!1,this.stopProgressAnimation(),this.updateProgressAnimation(),this.statusAnimation("paused"))};
TimeDisplay.prototype.tick=function(a){if(0<this._currentTime){this._lastSleepTime||(this._lastSleepTime=this._tickTime);var b=this._tickTime-((new Date).getTime()-a.getTime()-this._lastSleepTime);this._lastSleepTime=b;a=new Date;this._timeLabel.persistant=!0;createjs.Tween.get(this._timeLabel,{loop:!1}).wait(b).call(function(){this._running&&(0<this._currentTime&&(this._currentTime--,this.updateTimeLabel()),6>this._currentTime&&this.lowTimeAnimation(),this.tick(a))}.bind(this))}else this._running=
!1,null!=this._submit&&this._submit()};TimeDisplay.prototype.updateTimeLabel=function(){this._timeLabel.text=this._currentTime.toString()};TimeDisplay.prototype.changeTime=function(a){this.updateTime(this._currentTime+a)};
TimeDisplay.prototype.updateTime=function(a){var b=this._currentTime;this._currentTime=Math.max(Math.floor(a),0);this._currentTime>this._totalTime&&(this._totalTime=this._currentTime);this.updateTimeLabel();this.updateProgressAnimation();this._running&&this.startProgressAnimation();a=this._currentTime-b;this.statusAnimation(0<=a?"+"+a.toString():a.toString())};
TimeDisplay.prototype.startProgressAnimation=function(){createjs.Tween.get(this._progressArc,{loop:!1,override:!0}).to({rotation:-90},1E3*this._currentTime,createjs.Ease.getPowInOut(1))};TimeDisplay.prototype.stopProgressAnimation=function(){createjs.Tween.removeTweens(this._progressArc)};TimeDisplay.prototype.updateProgressAnimation=function(){this._progressArc.rotation=-90*(1+-this._currentTime/this._totalTime)};
TimeDisplay.prototype.lowTimeAnimation=function(){this._backgroundCircle.handleEvent=function(){this.updateCache()};createjs.Tween.get(this._backgroundCircle.filters[0],{loop:!1}).call(function(a){createjs.Ticker.addEventListener("tick",a)},[this._backgroundCircle]).to({redMultiplier:1.5,greenMultiplier:.3,blueMultiplier:.3},250).to({redMultiplier:1,greenMultiplier:1,blueMultiplier:1},250).call(function(a){createjs.Ticker.removeEventListener("tick",a)},[this._backgroundCircle])};
TimeDisplay.prototype.statusAnimation=function(a){var b=Math.floor(Math.max(this._container.width/25,this._container.height/25)),c=new createjs.Text;c.text=a.toString();c.font=b+"px Dimbo";c.color="#F0261B";c.x=-this._radius/2;c.y=this._radius;c.alpha=0;c.lineWidth=this._radius;c.textAlign="center";c.textBaseline="bottom";createjs.Tween.get(c,{loop:!1}).to({alpha:1},1E3,createjs.Ease.getPowInOut(1)).to({alpha:0},1E3,createjs.Ease.getPowInOut(1));createjs.Tween.get(c,{loop:!1}).to({y:0},2200,createjs.Ease.getPowInOut(2)).call(function(a,
b){a.removeChild(b)},[this._container,c]);this._container.addChild(c)};TimeDisplay.prototype.getTime=function(){return this._currentTime};var TitleDisplay=function(a){this._value=a};TitleDisplay.prototype.addTo=function(a){a.name="TitleDisplay";var b=.75*a.width,c=a.height/13,d=this.createLabel(b,c),b=this.createBackgroundPanel(b,c,d.getMeasuredHeight());a.addChild(b,d)};
TitleDisplay.prototype.createLabel=function(a,b){var c=Math.floor(Math.max(a/22+5,b/4+30)),d=new createjs.Text;d.text=this._value.toString();d.font=c+"px Dimbo";d.color="#f0261b";d.lineWidth=a-a/15;d.lineHeight=b;d.textAlign="center";for(d.textBaseline="middle";d.getMeasuredHeight()>2*b;)c-=2,d.font=c+"px Dimbo";return d};TitleDisplay.prototype.createBackgroundPanel=function(a,b,c){c=c/b*b+b/2;var d=new createjs.Shape;d.graphics.beginFill("#d3d3d3").drawRoundRect(0,0,a,c,b/2);d.x=-a/2;d.y=b/4-b;return d};
var TooltipInfo=function(a){this._size=25;this._padding=5;this._tooltip=a};TooltipInfo.prototype.addTo=function(a){a.name="TooltipInfo";this._infoIcon?Common.replaceLastClass(this._infoIcon.htmlElement,Common.toClassID(a.id)):this._infoIcon=this.createInfoIcon(this._tooltip,Common.toClassID(a.id));a.addChild(this._infoIcon)};
TooltipInfo.prototype.createInfoIcon=function(a,b){var c=document.createElement("template");c.innerHTML='<div class="'+b+'" style="padding:'+this._padding+"px; position:absolute; top:"+document.getElementById("header").offsetHeight+'px; left:0" rel="tooltip" title="'+a+'"><img src="img/info.png" width="'+this._size+'px" height="'+this._size+'px"/></div>';c=c.content.firstChild;$("#placeholder").append(c);$(document).ready(function(){initTooltip(b)});c=new createjs.DOMElement(c);c.x=-this._size-this._padding;
c.y=-this._padding;return c};var WordPairs=function(a,b,c){this._answers=a;this._line=new createjs.Shape;this._connections=new createjs.Shape;this._connectMap={};this._panelDictionary=[];this._onChange=b;this._solution=c;if(void 0!=c)for(var d in c)this._connectMap[d]=c[d].pair;this._initialized=!1};
WordPairs.prototype.addTo=function(a){a.name="WordPairs";this._initialized&&this.redrawConnections();var b=this._answers[0],c=this._answers[1],d=.4*a.height,e=d/b.length,b=this.createWordPanel(e,b,"left");b.x=.1*-a.width;b.y=-d/2;c=this.createWordPanel(e,c,"right");c.x=.1*a.width;c.y=-d/2;this._initialized||(this.redrawConnections(),this._initialized=!0);a.addChild(b,c,this._connections,this._line)};
WordPairs.prototype.createWordPanel=function(a,b,c){for(var d=new createjs.Container,e=0;e<b.length;e++){var f=b[e],g=this.createLabel(a,f,c);g.y+=e*a;var h=a/5,l=g.getMeasuredWidth()+h,m=g.getMeasuredHeight()+h,f=this.createPanel(l,m,h,f,c);f.y+=e*a;d.addChild(f,g)}return d};WordPairs.prototype.createLabel=function(a,b,c){a*=.5;var d=new createjs.Text;d.text=b.toString();d.font=a+"px Dimbo";d.color="#f0261b";d.textAlign="left"===c?"right":"left";d.textBaseline="middle";return d};
WordPairs.prototype.createPanel=function(a,b,c,d,e){function f(a){a.target.filters=[new createjs.ColorFilter(1,1,1,1,-25,-25,-25,0)];a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h);this._hoveredPanel=a.target}function g(a){a.target.filters=[new createjs.ColorFilter(1,1,1,1,0,0,0,0)];a.target.cache(0,0,a.target.graphics.command.w,a.target.graphics.command.h);this._hoveredPanel=null}function h(a){this._selectedPanel=a.target}function l(a){var b=this._selectedPanel.connectPoint,
c=this._line,b=this._selectedPanel.localToLocal(b[0],b[1],c);a=c.globalToLocal(a.rawX,a.rawY);c.graphics.clear().setStrokeStyle(3).beginStroke("black").moveTo(b.x,b.y).lineTo(a.x,a.y).endStroke()}function m(a){if(a.isTouch){this._hoveredPanel=null;for(var b in this._panelDictionary){var c=this._panelDictionary[b],d=c.globalToLocal(a.rawX,a.rawY);if(c.hitTest(d.x,d.y)){this._hoveredPanel=c;break}}}if(null!=this._hoveredPanel&&this._hoveredPanel.anchor!=this._selectedPanel.anchor){a="left"===this._selectedPanel.anchor?
this._selectedPanel.text:this._hoveredPanel.text;b="right"===this._selectedPanel.anchor?this._selectedPanel.text:this._hoveredPanel.text;for(var e in this._connectMap)if(this._connectMap[e]===b){delete this._connectMap[e];this.redrawConnections();break}this._connectMap[a]=b;this.redrawConnections()}this._selectedPanel=null;this._line.graphics.clear();this._onChange(this._connectMap)}var k=new createjs.Shape;k.text=d.toString();k.anchor=e;k.graphics.beginFill("#d3d3d3").drawRect(0,0,a,b);k.connectPoint=
"left"===e?[a,b/2]:[0,b/2];k.x="left"===e?-a+c/2:-c/2;k.y=-b/2;void 0!=this._onChange&&(k.on("mouseover",f.bind(this)),k.on("mouseout",g.bind(this)),k.on("mousedown",h.bind(this)),k.on("pressmove",l.bind(this)),k.on("pressup",m.bind(this)));return this._panelDictionary[k.text]=k};
WordPairs.prototype.drawConnection=function(a,b,c){a=this._panelDictionary[a];b=this._panelDictionary[b];var d=this._connections;a=a.localToLocal(a.connectPoint[0],a.connectPoint[1],d);b=b.localToLocal(b.connectPoint[0],b.connectPoint[1],d);d.graphics.setStrokeStyle(3).beginStroke(c).moveTo(a.x,a.y).lineTo(b.x,b.y).endStroke()};
WordPairs.prototype.redrawConnections=function(){this._connections.graphics.clear();for(var a in this._connectMap)void 0==this._solution?this.drawConnection(a,this._connectMap[a],"black"):this._solution[a].selected?this.drawConnection(a,this._connectMap[a],"green"):this.drawConnection(a,this._connectMap[a],"#f0261b")};var Discussion=function(a){this._data=a;this._drawable=[];this._submitted=this._initialized=!1};
Discussion.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/idle.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._drawable.push(new TitleDisplay(this._data.text));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new TextBox(this.sendAnswer.bind(this)));
break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer)}this._initialized=!0};Discussion.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
Discussion.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "TextBox":a.x=.5*b.width/window.devicePixelRatio,a.y=.8*b.height/window.devicePixelRatio}};
Discussion.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};Discussion.prototype.sendAnswer=function(a){this._submitted||(a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"answer" : '+JSON.stringify(a)+"}"),ServerConnection.send(a))};
Discussion.prototype.submit=function(){this._submitted||(this._submitted=!0,StageManager.handleActivityEnd(this))};var GuessTheImage=function(a){this._data=a;this._drawable=[];this._submitted=this._initialized=!1};
GuessTheImage.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/idle.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._hiddenImage=new HiddenImage(this._data.image,this._data.row,this._data.col,this.playFirework.bind(this));this._drawable.push(this._hiddenImage);this._fireworkEffect=new FireworkEffect;this._drawable.push(this._fireworkEffect);switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+
this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new TextBox(this.sendAnswer.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer)}this._initialized=!0};
GuessTheImage.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
GuessTheImage.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "HiddenImage":a.x=b.width/2;a.y=.45*b.height;break;case "TextBox":a.x=.5*b.width/window.devicePixelRatio,a.y=.8*b.height/window.devicePixelRatio}};
GuessTheImage.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;case "HiddenImage":0<a.value?this._hiddenImage.removeRandomTile(a.value):this._hiddenImage.uncoverAll();break;default:throw Error();}};
GuessTheImage.prototype.playFirework=function(){setTimeout(function(){this._fireworkEffect.explosionAnimation(50,.2*screen.width,.2*screen.height,2);this._fireworkEffect.explosionAnimation(50,.5*screen.width,.3*screen.height,2);this._fireworkEffect.explosionAnimation(50,.8*screen.width,.2*screen.height,2)}.bind(this),2E3)};
GuessTheImage.prototype.sendAnswer=function(a){this._submitted||(a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"answer" : '+JSON.stringify(a)+"}"),ServerConnection.send(a))};GuessTheImage.prototype.submit=function(){this._submitted||(this._submitted=!0,StageManager.handleActivityEnd(this))};var Highscore=function(a){this._data=a;this._drawable=[];this._initialized=!1};
Highscore.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/highscore.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay("Highscore"));this._ranklist=new HighscoreList(this._data.ranklist);this._drawable.push(this._ranklist);this._footerDisplay=this._data.best?new FooterTextDisplay("Best score in last round: "+this._data.best.name+" (+"+this._data.best.difference+")"):new FooterTextDisplay("");this._drawable.push(this._footerDisplay);
this._fireworkEffect=new FireworkEffect;this._drawable.push(this._fireworkEffect);this._initialized=!0};
Highscore.prototype.draw=function(a){this._initialized||(this.init(),setTimeout(function(){this._fireworkEffect.explosionAnimation(50,.2*a.width,.2*a.height,2);this._fireworkEffect.explosionAnimation(50,.5*a.width,.3*a.height,2);this._fireworkEffect.explosionAnimation(50,.8*a.width,.2*a.height,2)}.bind(this),1E3));this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
Highscore.prototype.update=function(a){switch(a.component){case "highscore":this._ranklist.update(a.ranklist);a.best&&this._footerDisplay.update("Best score in last round: "+a.best.name+" (+"+a.best.difference+")");break;default:throw Error();}};Highscore.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "HighscoreList":a.x=b.width/2;a.y=b.height/3;break;case "FooterTextDisplay":a.x=b.width/2,a.y=b.height}};
var Idle=function(a){this._data=a;this._drawable=[];this._initialized=!1};Idle.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/idle.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._initialized=!0};Idle.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
Idle.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2,a.y=b.height/5}};var MultipleChoiceFocus=function(a){this._data=a;this._currentItem=null;this._selected=[];this._drawable=[];this._submitted=this._initialized=!1};
MultipleChoiceFocus.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background3.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._labelIterator=
new LabelIterator(this._data.answers,this._data.interval,this.currentItem.bind(this));this._drawable.push(this._labelIterator);this._drawable.push(new RoundButton("Select !",this.select.bind(this)));this._drawable.push(new SubmitButton(this.submit.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._labelIterator=new LabelIterator(this._data.answers,1500,null),this._drawable.push(this._labelIterator),
this._drawable.push(new RoundButton("Select !",null))}this._initialized=!0};MultipleChoiceFocus.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
MultipleChoiceFocus.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "RoundButton":a.x=b.width/2;a.y=.75*b.height;break;case "LabelIterator":a.x=b.width/2;a.y=.45*b.height;break;case "SubmitButton":a.x=b.width,a.y=b.height}};
MultipleChoiceFocus.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};MultipleChoiceFocus.prototype.currentItem=function(a){this._currentItem=a;return-1<this._selected.indexOf(a)?!0:!1};
MultipleChoiceFocus.prototype.select=function(){var a=this._currentItem,b=this._selected.indexOf(a);-1<b?(this._selected.splice(b,1),this._labelIterator.updateColor(!1)):(this._selected.push(a),this._labelIterator.updateColor(!0))};
MultipleChoiceFocus.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd(this))}};var MultipleChoiceQuestion=function(a){this._data=a;this._selected=[];this._drawable=[];this._submitted=this._initialized=!1};
MultipleChoiceQuestion.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._data.image&&""!=this._data.image&&(this._hasDisplayImage=!0,this._drawable.push(new DisplayImage(this._data.image)));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));
this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new ButtonPanel(this._data.answers,this._hasDisplayImage,this.selected.bind(this),this._data.stats));this._drawable.push(new SubmitButton(this.submit.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._drawable.push(new ButtonPanel(this._data.answers,
this._hasDisplayImage,null,this._data.stats))}this._initialized=!0};MultipleChoiceQuestion.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
MultipleChoiceQuestion.prototype.setOrigin=function(a,b){var c=b.width>=b.height;switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "ButtonPanel":a.x=b.width/2;this._hasDisplayImage&&c&&(a.x+=b.width/4);a.y=.65*b.height;this._hasDisplayImage&&!c&&(a.y=.75*b.height);break;case "DisplayImage":c?(a.x=
b.width/4,a.y=.65*b.height):(a.x=b.width/2,a.y=.45*b.height);break;case "SubmitButton":a.x=b.width,a.y=b.height}};MultipleChoiceQuestion.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};MultipleChoiceQuestion.prototype.selected=function(a){this._selected=a};
MultipleChoiceQuestion.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd(this))}};var PointAndClick=function(a){this._data=a;this._selected=[];this._drawable=[];this._submitted=this._initialized=!1};
PointAndClick.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/europe.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new InteractiveImage(this._data.image,
this.selected.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._drawable.push(new InteractiveImage(this._data.image,null))}this._initialized=!0};PointAndClick.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
PointAndClick.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "InteractiveImage":a.x=b.width/2,a.y=.65*b.height}};
PointAndClick.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};PointAndClick.prototype.selected=function(a){this._selected=a;this.submit()};
PointAndClick.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd(this))}};var PointAndClickSolution=function(a){this._data=a;this._selected=[];this._drawable=[];this._submitted=this._initialized=!1};
PointAndClickSolution.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/europe.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._drawable.push(new InteractiveImage(this._data.image,null,this._data.stats));"student"===this._data.view&&this._drawable.push(new HeaderDisplay("Score: +"+this._data.score));this._initialized=!0};
PointAndClickSolution.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
PointAndClickSolution.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "InteractiveImage":a.x=b.width/2,a.y=.65*b.height}};var QuestionSolution=function(a){this._data=a;this._drawable=[];this._initialized=!1};
QuestionSolution.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._data.image&&""!=this._data.image&&(this._hasDisplayImage=!0,this._drawable.push(new DisplayImage(this._data.image)));this._drawable.push(new ButtonPanel(this._data.answers,this._hasDisplayImage,null,this._data.stats));
"student"===this._data.view&&this._drawable.push(new HeaderDisplay("Score: +"+this._data.score));this._initialized=!0};QuestionSolution.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
QuestionSolution.prototype.setOrigin=function(a,b){var c=b.width>=b.height;switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "ButtonPanel":a.x=b.width/2;this._hasDisplayImage&&c&&(a.x+=b.width/4);a.y=.67*b.height;this._hasDisplayImage&&!c&&(a.y=.8*b.height);break;case "DisplayImage":c?(a.x=b.width/4,a.y=.67*b.height):(a.x=b.width/2,a.y=.46*b.height);break;case "HeaderDisplay":a.x=
0,a.y=0}};var Race=function(a){this._data=a;this._drawable=[];this._initialized=!1};
Race.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/highscore.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay("Race"));this._rpd=new RaceProgressionDisplay(this._data.groups,this._data.steps);this._drawable.push(this._rpd);this._footerDisplay=new FooterTextDisplay("");this._drawable.push(this._footerDisplay);this._fireworkEffect=new FireworkEffect;this._drawable.push(this._fireworkEffect);this._initialized=!0};
Race.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};Race.prototype.update=function(a){switch(a.component){case "rpd":this._rpd.update(a.group,a.value)&&this._footerDisplay.update("Last move: "+a.group+" ("+(0<=a.value?"+"+a.value:a.value)+")");break;default:throw Error();}};
Race.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "RaceProgressionDisplay":a.x=b.width/2;a.y=b.height/3;break;case "FooterTextDisplay":a.x=b.width/2,a.y=b.height}};var SimpleFocus=function(a){this._data=a;this._selected=null;this._drawable=[];this._submitted=this._initialized=!1};
SimpleFocus.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background3.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new LabelIterator(this._data.answers,
this._data.interval,this.selected.bind(this)));this._drawable.push(new RoundButton("Stop !",this.submit.bind(this)));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._drawable.push(new LabelIterator(this._data.answers,1500,null)),this._drawable.push(new RoundButton("Stop !",null))}this._initialized=!0};
SimpleFocus.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
SimpleFocus.prototype.setOrigin=function(a,b){switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "RoundButton":a.x=b.width/2;a.y=.75*b.height;break;case "LabelIterator":a.x=b.width/2,a.y=.45*b.height}};
SimpleFocus.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};SimpleFocus.prototype.selected=function(a){this._selected=a};
SimpleFocus.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected)+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd(this))}};var SimpleQuestion=function(a){this._data=a;this._selected=[null];this._drawable=[];this._submitted=this._initialized=!1};
SimpleQuestion.prototype.init=function(){void 0==this._data.bg&&(this._data.bg="img/quiz-background.jpg");this._drawable.push(new BackgroundImage(this._data.bg));this._drawable.push(new TitleDisplay(this._data.text));this._drawable.push(new DifficultyMeter(this._data.difficulty));this._data.image&&""!=this._data.image&&(this._hasDisplayImage=!0,this._drawable.push(new DisplayImage(this._data.image)));switch(this._data.view){case "student":this._drawable.push(new HeaderDisplay("Score: "+this._data.score));
this._timer=new TimeDisplay(this._data.time,this.submit.bind(this));this._drawable.push(this._timer);this._drawable.push(new ButtonPanel(this._data.answers,this._hasDisplayImage,this.selected.bind(this),this._data.stats));this._drawable.push(new TooltipInfo("Carefully read the question and click on the right answer."));break;case "projector":this._drawable.push(new HeaderDisplay(this._data.screen)),this._timer=new TimeDisplay(this._data.time,null),this._drawable.push(this._timer),this._drawable.push(new ButtonPanel(this._data.answers,
this._hasDisplayImage,null,this._data.stats))}this._initialized=!0};SimpleQuestion.prototype.draw=function(a){this._initialized||this.init();this._drawable.forEach(function(b){var c=new createjs.Container;c.width=a.width;c.height=a.height;b.addTo(c);this.setOrigin(c,a);a.addChild(c)}.bind(this))};
SimpleQuestion.prototype.setOrigin=function(a,b){var c=b.width>=b.height;switch(a.name){case "BackgroundImage":a.x=0;a.y=0;break;case "HeaderDisplay":a.x=0;a.y=0;break;case "TimeDisplay":a.x=b.width;a.y=0;break;case "TitleDisplay":a.x=b.width/2;a.y=b.height/5;break;case "DifficultyMeter":a.x=b.width/2;a.y=b.height/20;break;case "ButtonPanel":a.x=b.width/2;this._hasDisplayImage&&c&&(a.x+=b.width/4);a.y=.67*b.height;this._hasDisplayImage&&!c&&(a.y=.8*b.height);break;case "DisplayImage":c?(a.x=b.width/
4,a.y=.67*b.height):(a.x=b.width/2,a.y=.46*b.height);break;case "TooltipInfo":a.x=b.width/window.devicePixelRatio,a.y=0/window.devicePixelRatio}};SimpleQuestion.prototype.update=function(a){switch(a.component){case "timer":"absolute"===a.type&&this._timer.updateTime(a.value);"relative"===a.type&&this._timer.changeTime(a.value);"pause"===a.type&&this._timer.stopTimer();"resume"===a.type&&this._timer.startTimer();break;default:throw Error();}};
SimpleQuestion.prototype.selected=function(a){this._selected=a;this.submit()};SimpleQuestion.prototype.submit=function(){if(!this._submitted){var a=JSON.parse('{"cmd" : "submit","activity" : "'+this._data.screen+'","id" : '+this._data.id+',"selected" : '+JSON.stringify(this._selected[0])+',"time-left" : '+this._timer.getTime()+"}");ServerConnection.send(a)&&(this._submitted=!0,StageManager.handleActivityEnd(this))}};var ServerConnection=function(){};
ServerConnection.send=function(a){console.log("To server: "+JSON.stringify(a));"function"==typeof sendJSON&&sendJSON(a);return!0};ServerConnection.receive=function(a){console.log("From server: "+JSON.stringify(a));MessageInterpreter.interpret(a);return!0};var StageManager=function(){};
StageManager.init=function(a){this._canvas=a;this._stage=null;this._tranScreens=new createjs.Container;this._overlay=new createjs.Container;this._activeOverlay=this._activeScreen=null;this._height=this._width=0;StageManager.updateSize();this._isInitialized=!0};StageManager.idle=function(){return StageManager.draw(new Idle(JSON.parse('{ "cmd":"show", "screen": "Idle", "text":"Waiting for an activity...", "bg":"img/idle.jpg" }')))};
StageManager.draw=function(a,b){if(!this._isInitialized||null==a)return!1;window.onkeydown=null;window.onkeyup=null;var c=StageManager.createScreenContainer();a.container=c;a.draw(c);b?StageManager.addOverlay(a):StageManager.transition(a);return!0};
StageManager.update=function(a){if(this._activeScreen&&(void 0==a.id||a.id==this._activeScreen._data.id))try{this._activeScreen.update(a)}catch(b){console.log("Update cannot be applied to the current screen.")}if(this._activeOverlay&&(void 0==a.id||a.id==this._activeOverlay._data.id))try{this._activeOverlay.update(a)}catch(b){console.log("Update cannot be applied to the current overlay.")}};
StageManager.createStage=function(){var a=new createjs.Stage(this._canvas);a.canvas.width=this._width;a.canvas.height=this._height;a.enableMouseOver(30);a.autoClear=!1;createjs.Touch.enable(a);createjs.Ticker.timingMode=createjs.Ticker.RAF;createjs.Ticker.addEventListener("tick",a);a.addChild(this._tranScreens);a.addChild(this._overlay);return a};StageManager.createScreenContainer=function(){var a=new createjs.Container;a.width=this._width;a.height=this._height;return a};
StageManager.updateSize=function(){var a=document.getElementById("header").offsetHeight,b=document.getElementById("footer").offsetHeight;this._width=window.innerWidth;this._height=window.innerHeight-(a+b);this._width*=window.devicePixelRatio;this._height*=window.devicePixelRatio};
StageManager.resize=function(){if(null==this._stage)return!1;StageManager.updateSize();var a=this._height;this._stage.canvas.width=this._width;this._stage.canvas.height=a;this._stage.update();StageManager.redrawScreen(this._activeScreen);this._activeOverlay&&StageManager.redrawScreen(this._activeOverlay);return!0};StageManager.redrawScreen=function(a){var b=a.container;Common.removeTweens(b,!1);b.removeAllChildren();b.width=this._stage.canvas.width;b.height=this._stage.canvas.height;a.draw(b)};
StageManager.addOverlay=function(a){this._activeOverlay=a;a=a.container;a.scaleX=a.scaleY=0;a.alpha=.5;this._overlay.addChild(a);StageManager.expandOverlay()};
StageManager.expandOverlay=function(){if(0<this._overlay.numChildren){1<this._overlay.numChildren&&Common.removeTweens(this._overlay.getChildAt(this._overlay.numChildren-2),!0);for(var a=0;a<this._overlay.numChildren-2;a++)Common.removeHTMLElements(this._overlay.getChildAt(a)),this._overlay.removeChildAt(a);createjs.Tween.get(this._activeOverlay.container,{loop:!1,override:!0}).to({scaleX:1,scaleY:1,alpha:1},1E3,createjs.Ease.getPowInOut(2)).call(function(){Common.removeHTMLElements(this._overlay.getChildAt(this._overlay.numChildren-
2));this._overlay.removeChildAt(this._overlay.numChildren-2)}.bind(this))}else console.log("Cannot expand overlay: There is no active overlay.")};StageManager.minifyOverlay=function(){null!=this._activeOverlay?createjs.Tween.get(this._activeOverlay.container,{loop:!1,override:!0}).to({scaleX:.25,scaleY:.25,alpha:1},1E3,createjs.Ease.getPowInOut(2)):console.log("Cannot minify overlay: There is no active overlay.")};
StageManager.removeOverlay=function(){this._activeOverlay?(Common.removeTweens(this._activeOverlay.container,!0),createjs.Tween.get(this._activeOverlay.container,{loop:!1,override:!0}).to({scaleX:0,scaleY:0,alpha:.5},500,createjs.Ease.getPowInOut(2)).call(function(){Common.removeHTMLElements(this._activeOverlay.container);this._overlay.removeChild(this._activeOverlay.container);this._activeOverlay=null}.bind(this))):console.log("Cannot remove overlay: There is no active overlay.")};
StageManager.handleActivityEnd=function(a){a._data.overlay?StageManager.removeOverlay():(StageManager.idle(),this._activeOverlay&&StageManager.expandOverlay())};
StageManager.transition=function(a){this._activeScreen=a;a=a.container;this._activeOverlay&&StageManager.minifyOverlay();if(null==this._stage)this._stage=this.createStage(),this._tranScreens.addChild(a);else{a.x-=a.width;this._tranScreens.getChildAt(0).x=0;this._tranScreens.addChildAt(a,0);Common.removeTweens(this._tranScreens.getChildAt(1),!0);for(a=1;a<this._tranScreens.numChildren-1;a++)Common.removeHTMLElements(this._tranScreens.getChildAt(a)),this._tranScreens.removeChildAt(a);createjs.Tween.get(this._tranScreens,
{loop:!1,override:!0}).to({x:this._stage.canvas.width},1E3,createjs.Ease.getPowInOut(2)).call(function(){Common.removeHTMLElements(this._tranScreens.getChildAt(1));this._tranScreens.removeChildAt(1);this._tranScreens.x=this._tranScreens.getChildAt(0).x=0}.bind(this))}};
function initTooltip(a){var b=!1,c=!1;$("[rel~=tooltip]").bind("mouseenter",function(){b=$(this);tip=b.attr("title");targetClass=b.attr("class");c=$('<div id="tooltip"></div>');if(!tip||""==tip)return!1;b.removeAttr("title");c.css("opacity",0).html(tip).appendTo("#placeholder");var a=function(){$(window).width()<1.5*c.outerWidth()?c.css("max-width",$(window).width()/2):c.css("max-width",340);var a=b.offset().left+b.outerWidth()/2-c.outerWidth()/2,d=b.offset().top-c.outerHeight()-20;0>a?(a=b.offset().left+
b.outerWidth()/2-20,c.addClass("left")):c.removeClass("left");a+c.outerWidth()>$(window).width()?(a=b.offset().left-c.outerWidth()+b.outerWidth()/2+20,c.addClass("right")):c.removeClass("right");0>d?(d=b.offset().top+b.outerHeight(),c.addClass("top")):c.removeClass("top");c.css({left:a,top:d+30}).addClass(targetClass).animate({top:"-=10",opacity:1},100)};a();$(window).resize(a);a=function(){c.animate({top:"+=10",opacity:0},100,function(){$(this).remove()});b.attr("title",tip)};b.bind("mouseleave",
a);c.bind("click",a)})};